import {createHash} from 'node:crypto';
import {createReadStream} from 'node:fs';
import {lstat,open,readFile} from 'node:fs/promises';
import path from 'node:path';
import {z} from 'zod';
import {AppError} from '../security/errors.js';
import {safeStorageName} from '../storage/names.js';

import titles from '../../../shared/native-titles.json' with {type:'json'};
export const nativeTitles:Readonly<Record<string,{contentId:string;name:string}>>=titles;
export const nativeTitleId='PPSA99051',nativeContentId='UP9000-PPSA99051_00-PS5LIBRARYHOMETE';
export type NativeAssetKind='package'|'playgo'|'delta';
export function nativeUpdateFolder(titleId:string){const title=nativeTitles[titleId];if(!title)throw new Error(`Unknown native title: ${titleId}`);return `${safeStorageName(title.name)} [${safeStorageName(titleId)}]`;}
export function nativeAssetFileName(titleId:string,kind:NativeAssetKind,hash:string){const role={package:'Full Update',playgo:'PlayGo CRC',delta:'Delta Update'}[kind],extension=kind==='playgo'?'crc':'pkg';return `${nativeUpdateFolder(titleId)} - ${role} - ${digest.parse(hash).slice(0,12)}.${extension}`;}
export async function nativeAssetPath(root:string,titleId:string,kind:NativeAssetKind,hash:string){const named=path.join(root,nativeAssetFileName(titleId,kind,hash));if(await lstat(named).catch(()=>null))return named;return path.join(root,`${hash}.${kind==='package'?'pkg':kind==='playgo'?'crc':'delta.pkg'}`);}
const digest=z.string().regex(/^[a-f0-9]{64}$/),version=z.string().regex(/^\d{2}\.\d{3}\.\d{3}$/),nativeRelease=z.object({schemaVersion:z.literal(1),titleId:z.string(),contentId:z.string(),contentVersion:version,baseContentVersion:version,revision:z.number().int().positive(),systemVersion:z.number().int().nonnegative().max(Number.MAX_SAFE_INTEGER),package:z.object({size:z.number().int().positive().max(Number.MAX_SAFE_INTEGER),sha256:digest,sha1:z.string().regex(/^[a-f0-9]{40}$/),digest}),playgo:z.object({size:z.number().int().positive().max(Number.MAX_SAFE_INTEGER),sha256:digest}),delta:z.object({size:z.number().int().positive().max(Number.MAX_SAFE_INTEGER),sha256:digest})}).superRefine((value,context)=>{if(!Object.hasOwn(nativeTitles,value.titleId)||nativeTitles[value.titleId]?.contentId!==value.contentId)context.addIssue({code:'custom',message:'Unregistered or mismatched native title'});if(value.contentVersion<=value.baseContentVersion)context.addIssue({code:'custom',message:'Native patch version must be newer than its base'});if(value.package.size%0x10000)context.addIssue({code:'custom',message:'Native update package must be aligned to 64 KiB'});if(value.playgo.size!==value.package.size/0x10000*4)context.addIssue({code:'custom',message:'Native update CRC must cover every 64-KiB block'});});
export type NativeRelease=z.infer<typeof nativeRelease>;

async function hashes(file:string){const sha256=createHash('sha256'),sha1=createHash('sha1');for await(const chunk of createReadStream(file)){sha256.update(chunk);sha1.update(chunk);}return {sha256:sha256.digest('hex'),sha1:sha1.digest('hex')};}
async function validDelta(file:string,size:number,contentId:string){const handle=await open(file,'r');try{const header=Buffer.alloc(0x80);if((await handle.read(header,0,header.length,0)).bytesRead!==header.length||!header.subarray(0,4).equals(Buffer.from([0x7f,0x43,0x4e,0x54]))||header.readUInt32BE(0x10)!==8||header.readUInt16BE(0x14)!==6||header.subarray(0x40,0x64).toString('ascii').replace(/\0.*$/,'')!==contentId||header.readUInt32BE(0x74)!==0x23)return false;const end=header.readBigUInt64BE(0x20)+header.readBigUInt64BE(0x28);if(end>BigInt(size-4)||end>BigInt(Number.MAX_SAFE_INTEGER))return false;const rlc=Buffer.alloc(4);return (await handle.read(rlc,0,4,Number(end))).bytesRead===4&&rlc.equals(Buffer.from([0x7f,0x52,0x4c,0x43]));}finally{await handle.close();}}
export const noNativeUpdate=(titleId=nativeTitleId)=>`<?xml version="1.0" encoding="UTF-8"?><title_patch ac_set_rev="0" nptitleid="${titleId}_00" schema_ver="1.0"><app_tag content_id="${nativeTitles[titleId]!.contentId}" name="${nativeTitles[titleId]!.name}" revision="0"></app_tag></title_patch>`;
export const xml=(value:string)=>value.replace(/[&<>"']/g,character=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'})[character]!);
export function nativeReleaseLoader(nativeRoot:string,titleId=nativeTitleId){const cached=new Map<string,{key:string;release:Promise<NativeRelease>}>();const generation=(info:{dev:number;ino:number;size:number;mtimeMs:number;ctimeMs:number})=>`${info.dev}:${info.ino}:${info.size}:${info.mtimeMs}:${info.ctimeMs}`;return async(revision?:number):Promise<NativeRelease|null>=>{const metadataFile=revision===undefined?path.join(nativeRoot,'latest.json'):path.join(nativeRoot,'releases',`${revision}.json`),info=await lstat(metadataFile).catch((error:NodeJS.ErrnoException)=>{if(error.code==='ENOENT')return null;throw error;});if(!info)return null;if(!info.isFile()||info.isSymbolicLink()||info.size>8192)throw new AppError('INVALID_NATIVE_UPDATE',409);let release:NativeRelease,body:Buffer;try{body=await readFile(metadataFile);if(body.length>8192)throw new Error();release=nativeRelease.parse(JSON.parse(body.toString('utf8')));if(release.titleId!==titleId||(revision!==undefined&&release.revision!==revision))throw new Error();}catch{throw new AppError('INVALID_NATIVE_UPDATE',409);}const [packageFile,crcFile,deltaFile]=await Promise.all([nativeAssetPath(nativeRoot,titleId,'package',release.package.sha256),nativeAssetPath(nativeRoot,titleId,'playgo',release.playgo.sha256),nativeAssetPath(nativeRoot,titleId,'delta',release.delta.sha256)]),[packageInfo,crcInfo,deltaInfo]=await Promise.all([lstat(packageFile).catch(()=>null),lstat(crcFile).catch(()=>null),lstat(deltaFile).catch(()=>null)]);if(!packageInfo?.isFile()||packageInfo.isSymbolicLink()||packageInfo.size!==release.package.size||!crcInfo?.isFile()||crcInfo.isSymbolicLink()||crcInfo.size!==release.playgo.size||!deltaInfo?.isFile()||deltaInfo.isSymbolicLink()||deltaInfo.size!==release.delta.size)throw new AppError('INVALID_NATIVE_UPDATE',409);const files=[metadataFile,packageFile,crcFile,deltaFile],before=[info,packageInfo,crcInfo,deltaInfo],key=createHash('sha256').update(body).digest('hex')+'|'+before.map(generation).join('|'),previous=cached.get(metadataFile);if(previous?.key===key)return previous.release;const verified=(async()=>{const [packageHashes,crcHashes,deltaHashes,deltaValid]=await Promise.all([hashes(packageFile),hashes(crcFile),hashes(deltaFile),validDelta(deltaFile,release.delta.size,release.contentId)]),after=await Promise.all(files.map(file=>lstat(file).catch(()=>null)));if(after.some((value,index)=>!value||generation(value)!==generation(before[index]!))||packageHashes.sha256!==release.package.sha256||packageHashes.sha1!==release.package.sha1||crcHashes.sha256!==release.playgo.sha256||deltaHashes.sha256!==release.delta.sha256||!deltaValid)throw new AppError('INVALID_NATIVE_UPDATE',409);return release;})(),entry={key,release:verified};cached.set(metadataFile,entry);void verified.catch(()=>{if(cached.get(metadataFile)===entry)cached.delete(metadataFile);});return verified;};}
