import type {FastifyInstance} from 'fastify';
import {randomUUID} from 'node:crypto';
import {z} from 'zod';
import type {Config} from '../config.js';
import {transaction,type DB} from '../db.js';
import {seal,unseal} from '../auth/credentials.js';
import type {Auth} from '../auth/routes.js';
import {AppError} from '../security/errors.js';
import type {Logger} from '../logging.js';

type Fetch=typeof fetch;
export class MasterError extends Error{constructor(public status:number,public code:string){super(code);}}
const masterErrorCodes=new Set(['ALREADY_CONNECTED','ALREADY_FRIENDS','ARCHIVE_COLLISION','ARCHIVE_CORRUPT','ARCHIVE_MISMATCH','ARCHIVE_SIZE_MISMATCH','ARCHIVE_UNAVAILABLE','AUTHORIZATION_CONSUMED','AUTHORIZATION_DENIED','AUTHORIZATION_EXPIRED','AUTHORIZATION_NOT_FOUND','AUTHORIZATION_PENDING','CHALLENGE_EXPIRED','CONNECTION_BANNED','CONNECTION_PENDING','CONNECTION_REVOKED','FORBIDDEN','FRIEND_REQUEST_EXISTS','FRIEND_REQUESTS_DISABLED','GAME_SESSION_ADAPTER_DISABLED','GAME_SESSION_FULL','HANDLE_UNAVAILABLE','INSUFFICIENT_SPACE','INTERNAL_ERROR','INVALID_ARCHIVE_BODY','INVALID_INPUT','INVALID_PORTABLE_ARCHIVE','NOT_FOUND','PASSKEY_REQUIRED','PASSKEY_VERIFICATION_FAILED','PUBLICATION_CHANGED','RECOVERY_FAILED','SAVE_QUOTA_EXCEEDED','TERMS_ACCEPTANCE_REQUIRED','TERMS_CHANGED','TOKEN_REUSE_DETECTED','UNAUTHORIZED','UPDATE_NOT_FOUND']);
const safeMasterError=(value:unknown)=>typeof value==='string'&&masterErrorCodes.has(value)?value:'MASTER_REQUEST_FAILED';
const nodeCipherContext=(url:string)=>`community-node:${url}`,deviceCipherContext=(url:string,userId:string)=>`community-device:${url}:${userId}`,sessionCipherContext=(url:string,userId:string)=>`community-session:${url}:${userId}`;
const openCommunityCipher=(encrypted:string,key:string,context:string)=>unseal(encrypted,key,encrypted.startsWith('v2:')?context:undefined);
const userRefreshes=new WeakMap<DB,Map<string,Promise<string>>>();
const connectionSchema=z.object({connectionId:z.string().uuid(),serverId:z.string().regex(/^srv_[A-Za-z0-9_-]{16}$/),status:z.enum(['PENDING','APPROVED','BANNED']),banReason:z.string().nullable().optional()});
const identityDeviceSchema=z.object({deviceCode:z.string().regex(/^[a-f0-9]{64}$/),userCode:z.string().regex(/^[A-HJ-NP-Z2-9]{8}$/),verificationUri:z.string().url(),verificationUriComplete:z.string().url(),expiresIn:z.number().int().min(60).max(3600),interval:z.number().int().min(1).max(60)}).strict();
const identitySessionSchema=z.object({account:z.object({id:z.string().uuid(),handle:z.string().regex(/^[a-z0-9_]{3,32}$/),displayName:z.string().min(1).max(80),friendRequestPolicy:z.enum(['EVERYONE','NOBODY'])}).strict(),accessToken:z.string().regex(/^[a-f0-9]{64}$/),accessTokenExpiresIn:z.number().int().min(60).max(3600),refreshToken:z.string().regex(/^[0-9a-f-]{36}\.[a-f0-9]{64}$/)}).strict();
const sealedDeviceSchema=z.object({userId:z.string().uuid(),deviceCode:z.string().regex(/^[a-f0-9]{64}$/)}).strict();
const sealedSessionSchema=z.object({userId:z.string().uuid(),accessToken:z.string().regex(/^[a-f0-9]{64}$/),accessExpiresAt:z.number().int().positive(),refreshToken:z.string().regex(/^[0-9a-f-]{36}\.[a-f0-9]{64}$/)}).strict();
const refreshedSessionSchema=identitySessionSchema.omit({account:true});
const friendSchema=z.object({id:z.string().uuid(),handle:z.string().regex(/^[a-z0-9_]{3,32}$/),displayName:z.string().min(1).max(80),friendsSince:z.string()}).strict();
const friendSessionSchema=z.object({id:z.string().uuid(),adapterId:z.string().regex(/^[a-z0-9][a-z0-9._-]{2,63}$/),gameTitleId:z.string().regex(/^[A-Z]{4}[0-9]{5}$/),gameVersion:z.string().regex(/^[A-Za-z0-9._-]{1,32}$/),playerCount:z.number().int().min(1).max(16),maxPlayers:z.number().int().min(2).max(16),expiresAt:z.string()}).strict();
const friendPresenceSchema=friendSchema.omit({friendsSince:true}).extend({state:z.enum(['ONLINE','AWAY','OFFLINE']),updatedAt:z.string().nullable(),session:friendSessionSchema.nullable().optional()}).strict();
const handle=z.string().trim().toLowerCase().regex(/^[a-z0-9_]{3,32}$/),friendIdentity=friendSchema.pick({id:true,handle:true,displayName:true});
const friendRequestsSchema=z.object({incoming:z.array(z.object({id:z.string().uuid(),createdAt:z.string(),from:friendIdentity}).strict()),outgoing:z.array(z.object({id:z.string().uuid(),createdAt:z.string(),to:friendIdentity}).strict())}).strict();
const gameAdapter=z.string().regex(/^[a-z0-9][a-z0-9._-]{2,63}$/),gameTitle=z.string().regex(/^[A-Z]{4}[0-9]{5}$/),gameVersion=z.string().regex(/^[A-Za-z0-9._-]{1,32}$/),gameSessionCreate=z.object({adapterId:gameAdapter,gameTitleId:gameTitle,gameVersion,maxPlayers:z.number().int().min(2).max(16),connectionData:z.string().regex(/^[A-Za-z0-9_-]{1,2048}$/)}).strict(),gameSessionQuery=gameSessionCreate.pick({adapterId:true,gameTitleId:true,gameVersion:true});
const gameSessionSchema=z.object({id:z.string().uuid(),adapterId:gameAdapter,gameTitleId:gameTitle,gameVersion,maxPlayers:z.number().int().min(2).max(16),playerCount:z.number().int().min(1).max(16),host:z.object({id:z.string().uuid(),handle,displayName:z.string().min(1).max(80)}).strict(),createdAt:z.string(),expiresAt:z.string(),connectionData:z.string().regex(/^[A-Za-z0-9_-]{1,2048}$/).optional()}).strict();

async function responseJson(response:Response){let size=0;const chunks:Uint8Array[]=[];if(response.body)for await(const chunk of response.body){size+=chunk.length;if(size>1024*1024)throw new AppError('MASTER_RESPONSE_TOO_LARGE',502);chunks.push(chunk);}const text=Buffer.concat(chunks).toString('utf8');return text?JSON.parse(text):{};}
export async function masterRequest(config:Config,route:string,options:{method?:string;body?:unknown;token?:string;userToken?:string}={},fetcher:Fetch=fetch){
  if(!config.COMMUNITY_MASTER_URL)throw new AppError('COMMUNITY_MASTER_NOT_CONFIGURED',409);const url=new URL(route,config.COMMUNITY_MASTER_URL);if(url.origin!==config.COMMUNITY_MASTER_URL)throw new AppError('INVALID_MASTER_ROUTE',500);
  const response=await fetcher(url,{method:options.method??'GET',redirect:'error',signal:AbortSignal.timeout(10_000),headers:{accept:'application/json',...(options.body?{'content-type':'application/json'}:{}),...(options.token?{authorization:`Bearer ${options.token}`}:{}) ,...(options.userToken?{'x-ps5library-user-token':options.userToken}:{})},body:options.body?JSON.stringify(options.body):undefined});
  const body=await responseJson(response).catch(error=>{if(error instanceof SyntaxError)throw new AppError('INVALID_MASTER_RESPONSE',502);throw error;});if(!response.ok)throw new MasterError(response.status,safeMasterError(body.error));return body;
}

export async function approvedMasterCredential(db:DB,config:Config){const row=(await db.query('SELECT credential_cipher,state,master_url FROM community_master_connection WHERE singleton')).rows[0];if(!row?.credential_cipher||row.state!=='APPROVED')throw new AppError('COMMUNITY_MASTER_NOT_APPROVED',409);if(row.master_url!==config.COMMUNITY_MASTER_URL)throw new AppError('COMMUNITY_MASTER_CHANGED',409);try{const token=z.string().regex(/^[a-f0-9]{64}$/).parse(openCommunityCipher(row.credential_cipher,config.BOOTSTRAP_TOKEN,nodeCipherContext(row.master_url)));if(!row.credential_cipher.startsWith('v2:'))await db.query('UPDATE community_master_connection SET credential_cipher=$2,updated_at=now() WHERE singleton AND credential_cipher=$1',[row.credential_cipher,seal(token,config.BOOTSTRAP_TOKEN,nodeCipherContext(row.master_url))]);return token;}catch{throw new AppError('COMMUNITY_CREDENTIAL_UNREADABLE',409);}}

export async function approvedMasterUserCredential(db:DB,config:Config,userId:string,fetcher:Fetch=fetch,allowPending=false){
  try{const load=async()=>{const row=(await db.query('SELECT * FROM community_user_connections WHERE user_id=$1',[userId])).rows[0];
    if(!row||(row.state!=='CONNECTED'&&!(allowPending&&row.state==='DISCONNECT_PENDING'))||!row.session_cipher)throw new AppError('COMMUNITY_ACCOUNT_NOT_CONNECTED',409);if(row.master_url!==config.COMMUNITY_MASTER_URL)throw new AppError('COMMUNITY_MASTER_CHANGED',409);
    let session:z.infer<typeof sealedSessionSchema>;try{session=sealedSessionSchema.parse(JSON.parse(openCommunityCipher(row.session_cipher,config.BOOTSTRAP_TOKEN,sessionCipherContext(row.master_url,userId))));}catch{throw new AppError('COMMUNITY_CREDENTIAL_UNREADABLE',409);}
    if(session.userId!==userId)throw new AppError('COMMUNITY_CREDENTIAL_UNREADABLE',409);if(!row.session_cipher.startsWith('v2:')){const upgraded=seal(JSON.stringify(session),config.BOOTSTRAP_TOKEN,sessionCipherContext(row.master_url,userId));if((await db.query('UPDATE community_user_connections SET session_cipher=$2,updated_at=now() WHERE user_id=$1 AND session_cipher=$3',[userId,upgraded,row.session_cipher])).rowCount)row.session_cipher=upgraded;}return {row,session};};
    const loaded=await load();if(loaded.session.accessExpiresAt>Date.now()+30_000)return loaded.session.accessToken;
    // ponytail: one Node process coalesces refresh rotation; use a distributed lock if Node replicas are introduced.
    let refreshes=userRefreshes.get(db);if(!refreshes){refreshes=new Map();userRefreshes.set(db,refreshes);}const active=refreshes.get(userId);if(active)return await active;
    const refresh=(async()=>{const current=await load();if(current.session.accessExpiresAt>Date.now()+30_000)return current.session.accessToken;const nodeToken=await approvedMasterCredential(db,config),refreshed=refreshedSessionSchema.parse(await masterRequest(config,'/api/v1/identity/refresh',{method:'POST',token:nodeToken,userToken:current.session.accessToken,body:{refreshToken:current.session.refreshToken}},fetcher)),next={userId,accessToken:refreshed.accessToken,accessExpiresAt:Date.now()+refreshed.accessTokenExpiresIn*1000,refreshToken:refreshed.refreshToken},cipher=seal(JSON.stringify(next),config.BOOTSTRAP_TOKEN,sessionCipherContext(current.row.master_url,userId));
      if((await db.query('UPDATE community_user_connections SET session_cipher=$2,error=NULL,updated_at=now() WHERE user_id=$1 AND session_cipher=$3 AND state=$4',[userId,cipher,current.row.session_cipher,current.row.state])).rowCount)return refreshed.accessToken;const winner=await load();if(winner.session.accessExpiresAt>Date.now()+30_000)return winner.session.accessToken;throw new AppError('COMMUNITY_SESSION_CHANGED',409);})();
    refreshes.set(userId,refresh);try{return await refresh;}finally{if(refreshes.get(userId)===refresh)refreshes.delete(userId);}
  }catch(error){if(error instanceof AppError)throw error;if(error instanceof MasterError){if(error.status===401)await db.query("UPDATE community_user_connections SET state='ERROR',session_cipher=NULL,error='REAUTHENTICATION_REQUIRED',updated_at=now() WHERE user_id=$1",[userId]);throw new AppError(error.status===401?'COMMUNITY_ACCOUNT_REAUTHENTICATION_REQUIRED':error.code,error.status);}if(error instanceof z.ZodError)throw new AppError('INVALID_MASTER_RESPONSE',502);throw new AppError('MASTER_UNREACHABLE',502);}
}

export async function communityRoutes(app:FastifyInstance,db:DB,config:Config,auth:Auth,logs:Logger,fetcher:Fetch=fetch){
  const admin=async(req:Parameters<Auth['user']>[0])=>{const user=await auth.user(req);if(user.role!=='ADMIN')throw new AppError('FORBIDDEN',403);return user;};
  const row=async()=>(await db.query('SELECT * FROM community_master_connection WHERE singleton')).rows[0];
  const view=(value:any)=>value?{configured:Boolean(config.COMMUNITY_MASTER_URL)&&config.features.community,displayName:value.display_name,serverId:value.server_identifier,state:value.state,userCode:value.state==='AWAITING_OWNER'?value.user_code:null,verificationUriComplete:value.state==='AWAITING_OWNER'?value.verification_uri_complete:null,expiresAt:value.expires_at,banReason:value.state==='BANNED'?value.ban_reason:null,error:value.error,updatedAt:value.updated_at}:{configured:Boolean(config.COMMUNITY_MASTER_URL)&&config.features.community,state:'DISCONNECTED'};
  const userRow=async(userId:string)=>(await db.query('SELECT * FROM community_user_connections WHERE user_id=$1',[userId])).rows[0];
  const userView=(value:any)=>value?{configured:Boolean(config.COMMUNITY_MASTER_URL)&&config.features.community,state:value.state,userCode:value.state==='AWAITING_OWNER'?value.user_code:null,verificationUriComplete:value.state==='AWAITING_OWNER'?value.verification_uri_complete:null,expiresAt:value.expires_at,account:value.master_account_id?{id:value.master_account_id,handle:value.master_handle,displayName:value.master_display_name}:null,error:value.error,updatedAt:value.updated_at}:{configured:Boolean(config.COMMUNITY_MASTER_URL)&&config.features.community,state:'DISCONNECTED',account:null};
  const queueAccountNotice=async(userId:string,consoleId:string,value:any)=>{
    let code='',context='',message='';
    if(value?.state==='CONNECTED'&&value.master_account_id&&value.master_handle){code='COMMUNITY_CONNECTED';context=`account:${value.master_account_id}`;message=`Welcome to the PS5Library Store. Your Community account @${value.master_handle} is connected.`;}
    else if(value?.state==='ERROR'&&value.error){const reasons:Record<string,string>={AUTHORIZATION_EXPIRED:'the sign-in code expired',AUTHORIZATION_DENIED:'the sign-in request was declined',AUTHORIZATION_NOT_FOUND:'the sign-in request no longer exists',AUTHORIZATION_CONSUMED:'the sign-in code was already used',CHALLENGE_EXPIRED:'the passkey request expired',PASSKEY_VERIFICATION_FAILED:'the passkey could not be verified',CREDENTIAL_UNREADABLE:'the saved sign-in could not be opened',COMMUNITY_CREDENTIAL_UNREADABLE:'the saved sign-in could not be opened',REAUTHENTICATION_REQUIRED:'the saved session expired',MASTER_UNREACHABLE:'the Community server could not be reached',INVALID_MASTER_RESPONSE:'the Community server returned an invalid response',UNAUTHORIZED:'the Community session was rejected'};code='COMMUNITY_LOGIN_FAILED';context=`error:${new Date(value.updated_at).toISOString()}`;message=`PS5Library Community sign-in failed because ${reasons[value.error]??'the Community server rejected the request'}. Open Profile > Community and try again.`;}
    if(!code)return;
    await db.query(`INSERT INTO console_notices(id,user_id,console_id,release_id,code,context,message,resolve_on_delivery)
      SELECT $1,$2,$3,NULL,$4,$5,$6,true WHERE EXISTS(SELECT 1 FROM consoles WHERE id=$3 AND user_id=$2)
      AND NOT EXISTS(SELECT 1 FROM console_notices WHERE console_id=$3 AND code=$4 AND context=$5)`,[randomUUID(),userId,consoleId,code,context,message]);
  };
  const userToken=(userId:string,allowPending=false)=>approvedMasterUserCredential(db,config,userId,fetcher,allowPending);
  const parsed=<T>(schema:z.ZodType<T>,value:unknown)=>{const result=schema.safeParse(value);if(!result.success)throw new AppError('INVALID_MASTER_RESPONSE',502);return result.data;};
  const userRequest=async(userId:string,route:string,options:{method?:string;body?:unknown}={})=>{const [userCredential,nodeCredential]=await Promise.all([userToken(userId),approvedMasterCredential(db,config)]);try{return await masterRequest(config,route,{...options,token:nodeCredential,userToken:userCredential},fetcher);}catch(error){if(error instanceof AppError)throw error;if(error instanceof MasterError){if(error.status===401)await db.query("UPDATE community_user_connections SET state='ERROR',session_cipher=NULL,error='REAUTHENTICATION_REQUIRED',updated_at=now() WHERE user_id=$1",[userId]);throw new AppError(error.status===401?'COMMUNITY_ACCOUNT_REAUTHENTICATION_REQUIRED':error.code,error.status);}throw new AppError('MASTER_UNREACHABLE',502);}};
  const friendsPresence=async(userId:string)=>parsed(z.array(friendPresenceSchema),await userRequest(userId,'/api/v1/friends/presence'));
  const setPresence=async(userId:string,state:'ONLINE'|'AWAY'|null)=>{await userRequest(userId,'/api/v1/presence',{method:state?'PUT':'DELETE',...(state?{body:{state}}:{})});};
  const gameSessions=async(userId:string,value:unknown)=>{const query=gameSessionQuery.parse(value),search=new URLSearchParams(query);return parsed(z.array(gameSessionSchema),await userRequest(userId,`/api/v1/game-sessions?${search}`));};
  const createGameSession=async(userId:string,value:unknown)=>parsed(gameSessionSchema,await userRequest(userId,'/api/v1/game-sessions',{method:'POST',body:gameSessionCreate.parse(value)}));
  const gameSessionAction=async(userId:string,id:string,action:'join'|'heartbeat'|'close')=>{const route=`/api/v1/game-sessions/${z.string().uuid().parse(id)}${action==='close'?'':`/${action}`}`,method=action==='join'?'POST':action==='heartbeat'?'PUT':'DELETE',result=await userRequest(userId,route,{method});return action==='join'?parsed(gameSessionSchema,result):null;};
  const poll=async()=>{
    const current=await row();if(!current?.credential_cipher||current.state==='DISCONNECTED')return current;
    if(current.master_url!==config.COMMUNITY_MASTER_URL){await db.query("UPDATE community_master_connection SET state='ERROR',error='COMMUNITY_MASTER_CHANGED',updated_at=now() WHERE singleton");return row();}
    let token:string;try{token=z.string().regex(/^[a-f0-9]{64}$/).parse(openCommunityCipher(current.credential_cipher,config.BOOTSTRAP_TOKEN,nodeCipherContext(current.master_url)));if(!current.credential_cipher.startsWith('v2:'))await db.query('UPDATE community_master_connection SET credential_cipher=$2,updated_at=now() WHERE singleton AND credential_cipher=$1',[current.credential_cipher,seal(token,config.BOOTSTRAP_TOKEN,nodeCipherContext(current.master_url))]);}catch{await db.query("UPDATE community_master_connection SET state='ERROR',error='CREDENTIAL_UNREADABLE',updated_at=now() WHERE singleton");return row();}
    if(current.state==='DISCONNECT_PENDING')try{await masterRequest(config,'/api/v1/connection',{method:'DELETE',token},fetcher);await transaction(db,async sql=>{await sql.query("UPDATE community_master_connection SET credential_cipher=NULL,state='DISCONNECTED',error=NULL,updated_at=now() WHERE singleton");await sql.query("UPDATE community_user_connections SET state='DISCONNECTED',device_code_cipher=NULL,session_cipher=NULL,user_code=NULL,verification_uri=NULL,verification_uri_complete=NULL,error=NULL,updated_at=now()");});return row();}catch(error){const code=error instanceof MasterError?error.code:'MASTER_UNREACHABLE';await db.query('UPDATE community_master_connection SET error=$1,updated_at=now() WHERE singleton',[code]);return row();}
    try{
      const result=current.server_identifier?connectionSchema.pick({serverId:true,status:true,banReason:true}).parse(await masterRequest(config,'/api/v1/connections/status',{token},fetcher)):
        connectionSchema.parse(await masterRequest(config,'/api/v1/device-authorizations/token',{method:'POST',body:{deviceCode:token}},fetcher));
      await db.query(`UPDATE community_master_connection SET server_identifier=$1,state=$2,ban_reason=$3,error=NULL,user_code=NULL,verification_uri=NULL,verification_uri_complete=NULL,updated_at=now() WHERE singleton`,[result.serverId,result.status,result.banReason??null]);
      if(current.state!==result.status)await logs.write('INFO','community.state_changed',`Community connection is ${result.status}`,{serverId:result.serverId,state:result.status});
    }catch(error){
      if(error instanceof MasterError&&error.code==='AUTHORIZATION_PENDING')return current;
      const code=error instanceof MasterError?error.code:error instanceof AppError?error.code:'MASTER_UNREACHABLE';await db.query("UPDATE community_master_connection SET state=CASE WHEN state='DISCONNECT_PENDING' THEN state ELSE 'ERROR' END,error=$1,updated_at=now() WHERE singleton",[code]);await logs.write('WARN','community.poll_failed',code);
    }
    return row();
  };

  app.get('/api/v1/admin/community',async req=>{await admin(req);return view(config.features.community?await poll():await row());});
  app.post('/api/v1/admin/community/request',{config:{rateLimit:{max:5,timeWindow:'1 minute'}}},async(req,reply)=>{
    const user=await admin(req),{displayName}=z.object({displayName:z.string().trim().min(1).max(80)}).strict().parse(req.body);if(!config.COMMUNITY_MASTER_URL)throw new AppError('COMMUNITY_MASTER_NOT_CONFIGURED',409);
    const existing=await row(),installationId=existing?.installation_id??randomUUID(),created=z.object({deviceCode:z.string().regex(/^[a-f0-9]{64}$/),userCode:z.string().regex(/^[A-HJ-NP-Z2-9]{8}$/),verificationUri:z.string().url(),verificationUriComplete:z.string().url(),expiresIn:z.number().int().min(60).max(3600)}).parse(await masterRequest(config,'/api/v1/device-authorizations',{method:'POST',body:{installationId,displayName}},fetcher));
    for(const location of [created.verificationUri,created.verificationUriComplete])if(new URL(location).origin!==config.COMMUNITY_MASTER_URL)throw new AppError('INVALID_MASTER_RESPONSE',502);
    await db.query(`INSERT INTO community_master_connection(singleton,installation_id,master_url,display_name,credential_cipher,user_code,verification_uri,verification_uri_complete,state,expires_at,error,updated_at)
      VALUES(true,$1,$2,$3,$4,$5,$6,$7,'AWAITING_OWNER',now()+$8*interval '1 second',NULL,now()) ON CONFLICT(singleton) DO UPDATE SET installation_id=EXCLUDED.installation_id,master_url=EXCLUDED.master_url,display_name=EXCLUDED.display_name,
      credential_cipher=EXCLUDED.credential_cipher,user_code=EXCLUDED.user_code,verification_uri=EXCLUDED.verification_uri,verification_uri_complete=EXCLUDED.verification_uri_complete,server_identifier=NULL,state='AWAITING_OWNER',ban_reason=NULL,expires_at=EXCLUDED.expires_at,error=NULL,updated_at=now()`,[installationId,config.COMMUNITY_MASTER_URL,displayName,seal(created.deviceCode,config.BOOTSTRAP_TOKEN,nodeCipherContext(config.COMMUNITY_MASTER_URL)),created.userCode,created.verificationUri,created.verificationUriComplete,created.expiresIn]);
    await logs.write('INFO','community.access_requested',`Community access requested by ${user.username}`,{state:'AWAITING_OWNER'});return reply.code(202).send(view(await row()));
  });
  app.post('/api/v1/admin/community/refresh',async req=>{await admin(req);return view(await poll());});
  app.delete('/api/v1/admin/community',async(req,reply)=>{const user=await admin(req),current=await row();if(!current)return reply.code(204).send();
    if(current.credential_cipher&&current.master_url!==config.COMMUNITY_MASTER_URL){await transaction(db,async sql=>{await sql.query("UPDATE community_master_connection SET state='DISCONNECT_PENDING',error='COMMUNITY_MASTER_CHANGED',updated_at=now() WHERE singleton");await sql.query("UPDATE community_user_connections SET state='DISCONNECTED',device_code_cipher=NULL,session_cipher=NULL,user_code=NULL,verification_uri=NULL,verification_uri_complete=NULL,error=NULL,updated_at=now()");});return reply.code(202).send(view(await row()));}
    if(current.credential_cipher){let token='';try{token=z.string().regex(/^[a-f0-9]{64}$/).parse(openCommunityCipher(current.credential_cipher,config.BOOTSTRAP_TOKEN,nodeCipherContext(current.master_url)));}catch{await db.query("UPDATE community_master_connection SET state='DISCONNECT_PENDING',error='CREDENTIAL_UNREADABLE',updated_at=now() WHERE singleton");return reply.code(202).send(view(await row()));}try{await masterRequest(config,'/api/v1/connection',{method:'DELETE',token},fetcher);}catch(error){const code=error instanceof MasterError?error.code:'MASTER_UNREACHABLE';await db.query("UPDATE community_master_connection SET state='DISCONNECT_PENDING',error=$1,updated_at=now() WHERE singleton",[code]);await logs.write('WARN','community.disconnect_pending',code);return reply.code(202).send(view(await row()));}}
    await transaction(db,async sql=>{await sql.query("UPDATE community_master_connection SET credential_cipher=NULL,user_code=NULL,verification_uri=NULL,verification_uri_complete=NULL,state='DISCONNECTED',error=NULL,updated_at=now() WHERE singleton");await sql.query("UPDATE community_user_connections SET state='DISCONNECTED',device_code_cipher=NULL,session_cipher=NULL,user_code=NULL,verification_uri=NULL,verification_uri_complete=NULL,error=NULL,updated_at=now()");});await logs.write('INFO','community.disconnected',`Community disconnected by ${user.username}`);return {ok:true};});

  app.get('/api/v1/community/account',async req=>userView(await userRow((await auth.user(req)).id)));
  app.post('/api/v1/community/account/request',{config:{rateLimit:{max:5,timeWindow:'1 minute'}}},async(req,reply)=>{
    const user=await auth.user(req),{deviceName}=z.object({deviceName:z.string().trim().min(1).max(80)}).strict().parse(req.body);if(!config.COMMUNITY_MASTER_URL)throw new AppError('COMMUNITY_MASTER_NOT_CONFIGURED',409);
    const nodeToken=await approvedMasterCredential(db,config),created=identityDeviceSchema.parse(await masterRequest(config,'/api/v1/identity/device-sessions',{method:'POST',token:nodeToken,body:{deviceName}},fetcher));
    for(const location of [created.verificationUri,created.verificationUriComplete])if(new URL(location).origin!==config.COMMUNITY_MASTER_URL)throw new AppError('INVALID_MASTER_RESPONSE',502);
    const cipher=seal(JSON.stringify({userId:user.id,deviceCode:created.deviceCode}),config.BOOTSTRAP_TOKEN,deviceCipherContext(config.COMMUNITY_MASTER_URL,user.id));
    await db.query(`INSERT INTO community_user_connections(user_id,master_url,state,device_code_cipher,user_code,verification_uri,verification_uri_complete,expires_at,error,updated_at)
      VALUES($1,$2,'AWAITING_OWNER',$3,$4,$5,$6,now()+$7*interval '1 second',NULL,now()) ON CONFLICT(user_id) DO UPDATE SET master_url=EXCLUDED.master_url,state='AWAITING_OWNER',device_code_cipher=EXCLUDED.device_code_cipher,
      session_cipher=NULL,user_code=EXCLUDED.user_code,verification_uri=EXCLUDED.verification_uri,verification_uri_complete=EXCLUDED.verification_uri_complete,expires_at=EXCLUDED.expires_at,master_account_id=NULL,master_handle=NULL,master_display_name=NULL,error=NULL,updated_at=now()`,
      [user.id,config.COMMUNITY_MASTER_URL,cipher,created.userCode,created.verificationUri,created.verificationUriComplete,created.expiresIn]);
    await logs.write('INFO','community.user_link_requested',`Community identity requested by ${user.username}`);return reply.code(202).send(userView(await userRow(user.id)));
  });
  app.post('/api/v1/community/account/refresh',async req=>{
    const user=await auth.user(req),current=await userRow(user.id);if(!current)return userView(current);if(current.master_url!==config.COMMUNITY_MASTER_URL)throw new AppError('COMMUNITY_MASTER_CHANGED',409);if(current.state!=='AWAITING_OWNER'||!current.device_code_cipher)return userView(current);
    let deviceCode:string;try{const sealed=sealedDeviceSchema.parse(JSON.parse(openCommunityCipher(current.device_code_cipher,config.BOOTSTRAP_TOKEN,deviceCipherContext(current.master_url,user.id))));if(sealed.userId!==user.id)throw new Error('owner mismatch');deviceCode=sealed.deviceCode;if(!current.device_code_cipher.startsWith('v2:'))await db.query('UPDATE community_user_connections SET device_code_cipher=$2,updated_at=now() WHERE user_id=$1 AND device_code_cipher=$3',[user.id,seal(JSON.stringify(sealed),config.BOOTSTRAP_TOKEN,deviceCipherContext(current.master_url,user.id)),current.device_code_cipher]);}catch{await db.query("UPDATE community_user_connections SET state='ERROR',error='CREDENTIAL_UNREADABLE',updated_at=now() WHERE user_id=$1",[user.id]);return userView(await userRow(user.id));}
    try{const nodeToken=await approvedMasterCredential(db,config),result=identitySessionSchema.parse(await masterRequest(config,'/api/v1/identity/device-sessions/token',{method:'POST',token:nodeToken,body:{deviceCode}},fetcher)),sessionCipher=seal(JSON.stringify({userId:user.id,accessToken:result.accessToken,accessExpiresAt:Date.now()+result.accessTokenExpiresIn*1000,refreshToken:result.refreshToken}),config.BOOTSTRAP_TOKEN,sessionCipherContext(current.master_url,user.id));
      await db.query(`UPDATE community_user_connections SET state='CONNECTED',device_code_cipher=NULL,session_cipher=$2,user_code=NULL,verification_uri=NULL,verification_uri_complete=NULL,expires_at=NULL,
        master_account_id=$3,master_handle=$4,master_display_name=$5,error=NULL,updated_at=now() WHERE user_id=$1`,[user.id,sessionCipher,result.account.id,result.account.handle,result.account.displayName]);
      await logs.write('INFO','community.user_linked',`Community identity linked by ${user.username}`,{masterAccountId:result.account.id});
    }catch(error){if(error instanceof MasterError&&error.code==='AUTHORIZATION_PENDING')return userView(current);const code=error instanceof MasterError?error.code:'MASTER_UNREACHABLE';await db.query("UPDATE community_user_connections SET state='ERROR',error=$2,updated_at=now() WHERE user_id=$1",[user.id,code]);}
    return userView(await userRow(user.id));
  });
  app.delete('/api/v1/community/account',async(req,reply)=>{const user=await auth.user(req),current=await userRow(user.id);if(!current)return userView(current);
    if(current.state==='CONNECTED'||current.state==='DISCONNECT_PENDING')try{const [userCredential,nodeCredential]=await Promise.all([userToken(user.id,true),approvedMasterCredential(db,config)]);await masterRequest(config,'/api/v1/identity/logout',{method:'POST',token:nodeCredential,userToken:userCredential},fetcher);}catch(error){const code=error instanceof MasterError?error.code:error instanceof AppError?error.code:'MASTER_UNREACHABLE';
      if(!['COMMUNITY_ACCOUNT_REAUTHENTICATION_REQUIRED','COMMUNITY_CREDENTIAL_UNREADABLE'].includes(code)){await db.query("UPDATE community_user_connections SET state='DISCONNECT_PENDING',error=$2,updated_at=now() WHERE user_id=$1",[user.id,code]);return reply.code(202).send(userView(await userRow(user.id)));}}
    await db.query(`UPDATE community_user_connections SET state='DISCONNECTED',device_code_cipher=NULL,session_cipher=NULL,user_code=NULL,verification_uri=NULL,verification_uri_complete=NULL,expires_at=NULL,
      master_account_id=NULL,master_handle=NULL,master_display_name=NULL,error=NULL,updated_at=now() WHERE user_id=$1`,[user.id]);await logs.write('INFO','community.user_disconnected',`Community identity disconnected by ${user.username}`);return userView(await userRow(user.id));});
  app.get('/api/v1/community/friends',async req=>parsed(z.array(friendSchema),await userRequest((await auth.user(req)).id,'/api/v1/friends')));
  app.get('/api/v1/community/friends/presence',async req=>friendsPresence((await auth.user(req)).id));
  app.get('/api/v1/community/friends/requests',async req=>parsed(friendRequestsSchema,await userRequest((await auth.user(req)).id,'/api/v1/friends/requests')));
  app.post('/api/v1/community/friends/requests',async(req,reply)=>{const body=z.object({handle}).strict().parse(req.body),result=parsed(z.object({id:z.string().uuid()}).strict(),await userRequest((await auth.user(req)).id,'/api/v1/friends/requests',{method:'POST',body}));return reply.code(201).send(result);});
  app.post('/api/v1/community/friends/requests/:id/accept',async(req,reply)=>{const {id}=z.object({id:z.string().uuid()}).parse(req.params);await userRequest((await auth.user(req)).id,`/api/v1/friends/requests/${id}/accept`,{method:'POST'});return reply.code(204).send();});
  app.post('/api/v1/community/friends/requests/:id/decline',async(req,reply)=>{const {id}=z.object({id:z.string().uuid()}).parse(req.params);await userRequest((await auth.user(req)).id,`/api/v1/friends/requests/${id}/decline`,{method:'POST'});return reply.code(204).send();});
  app.delete('/api/v1/community/friends/requests/:id',async(req,reply)=>{const {id}=z.object({id:z.string().uuid()}).parse(req.params);await userRequest((await auth.user(req)).id,`/api/v1/friends/requests/${id}`,{method:'DELETE'});return reply.code(204).send();});
  app.delete('/api/v1/community/friends/:handle',async(req,reply)=>{const target=z.object({handle}).parse(req.params).handle;await userRequest((await auth.user(req)).id,`/api/v1/friends/${encodeURIComponent(target)}`,{method:'DELETE'});return reply.code(204).send();});
  app.put('/api/v1/community/presence',async(req,reply)=>{const state=z.object({state:z.enum(['ONLINE','AWAY'])}).strict().parse(req.body).state;await setPresence((await auth.user(req)).id,state);return reply.code(204).send();});
  app.delete('/api/v1/community/presence',async(req,reply)=>{await setPresence((await auth.user(req)).id,null);return reply.code(204).send();});
  app.get('/api/v1/community/game-sessions',async req=>gameSessions((await auth.user(req)).id,req.query));
  app.post('/api/v1/community/game-sessions',async(req,reply)=>reply.code(201).send(await createGameSession((await auth.user(req)).id,req.body)));
  app.post('/api/v1/community/game-sessions/:id/join',async req=>gameSessionAction((await auth.user(req)).id,(req.params as {id:string}).id,'join'));
  app.put('/api/v1/community/game-sessions/:id/heartbeat',async(req,reply)=>{await gameSessionAction((await auth.user(req)).id,(req.params as {id:string}).id,'heartbeat');return reply.code(204).send();});
  app.delete('/api/v1/community/game-sessions/:id',async(req,reply)=>{await gameSessionAction((await auth.user(req)).id,(req.params as {id:string}).id,'close');return reply.code(204).send();});
  app.get('/api/v1/device/community/account',async req=>{const device=await auth.device(req),current=await userRow(device.user_id);await queueAccountNotice(device.user_id,device.id,current);return userView(current);});
  app.get('/api/v1/device/community/friends/presence',async req=>friendsPresence((await auth.device(req)).user_id));
  app.put('/api/v1/device/community/presence',async(req,reply)=>{const state=z.object({state:z.enum(['ONLINE','AWAY'])}).strict().parse(req.body).state;await setPresence((await auth.device(req)).user_id,state);return reply.code(204).send();});
  app.delete('/api/v1/device/community/presence',async(req,reply)=>{await setPresence((await auth.device(req)).user_id,null);return reply.code(204).send();});
  app.get('/api/v1/device/community/game-sessions',async req=>gameSessions((await auth.device(req)).user_id,req.query));
  app.post('/api/v1/device/community/game-sessions',async(req,reply)=>reply.code(201).send(await createGameSession((await auth.device(req)).user_id,req.body)));
  app.post('/api/v1/device/community/game-sessions/:id/join',async req=>gameSessionAction((await auth.device(req)).user_id,(req.params as {id:string}).id,'join'));
  app.put('/api/v1/device/community/game-sessions/:id/heartbeat',async(req,reply)=>{await gameSessionAction((await auth.device(req)).user_id,(req.params as {id:string}).id,'heartbeat');return reply.code(204).send();});
  app.delete('/api/v1/device/community/game-sessions/:id',async(req,reply)=>{await gameSessionAction((await auth.device(req)).user_id,(req.params as {id:string}).id,'close');return reply.code(204).send();});
}
