import type {FastifyInstance} from 'fastify';
import {createHash,randomUUID} from 'node:crypto';
import {lstat,mkdir,open,rename,rm,type FileHandle} from 'node:fs/promises';
import path from 'node:path';
import {z} from 'zod';
import type {Auth} from '../auth/routes.js';
import type {Config} from '../config.js';
import {transaction,type DB} from '../db.js';
import {presence} from '../library/policy.js';
import {AppError} from '../security/errors.js';
import {fileHandleHash,regularFile,within} from '../security/paths.js';
import type {Logger} from '../logging.js';
import {bytes,localUserId,saveDirectory,savePlatform,sha256,titleId,uploadChunk,uuid} from '../../../shared/schemas/index.js';
import {communitySaveManifestSchema} from '../../../shared/schemas/community.js';
import {validatePortableSaveArchive} from '../../../shared/saves/portable.js';
import {quotaExceeded,requireDiskSpace,storageUsage} from '../storage/usage.js';
import {approvedMasterCredential,approvedMasterUserCredential,masterRequest} from './routes.js';
import {consoleSaveData} from '../consoles/save-data.js';
import {appendUpload,resumeUpload} from '../storage/upload.js';
import {serveStoredFile} from '../downloads/serve.js';

type Fetch=typeof fetch;
const version=z.string().min(1).max(32).regex(/^[A-Za-z0-9._-]+$/);
const exportRequest=z.object({localUserId,platform:savePlatform,gameTitleId:titleId,saveTitleId:titleId,directory:saveDirectory,gameVersion:version,region:z.string().min(1).max(32).regex(/^[A-Za-z0-9._-]+$/).optional()}).strict();
const start=z.object({totalBytes:bytes.min(1).max(8*1024**3),sha256,manifest:communitySaveManifestSchema}).strict();
const failure=z.object({error:z.enum(['SAVE_SOURCE_UNAVAILABLE','SAVE_SOURCE_CHANGED','INSUFFICIENT_SPACE','SAVE_EXPORT_FAILED','SAVE_IMPORT_FAILED','ROLLBACK_FAILED','CORRUPT_INPUT','CAPABILITY_UNAVAILABLE'])}).strict();
const importProgress=z.object({downloadedBytes:bytes,speedBytesPerSecond:bytes.default(0)}).strict();
const terms=z.object({accepted:z.literal(true),termsVersion:z.string().min(1).max(40),termsSha256:sha256}).strict();
const publication=z.object({displayName:z.string().trim().min(1).max(120),description:z.string().trim().max(2000).default('')}).strict();
const masterTerms=z.object({version:z.string().min(1).max(40),sha256,body:z.string().min(40).max(50_000),acceptLabel:z.string().min(1).max(300)});
const masterCatalog=z.object({gameTitleId:titleId,versions:z.array(z.object({gameVersion:version,saves:z.array(z.object({id:uuid,platform:z.enum(['PS4','PS5']),gameTitleId:titleId,saveTitleId:titleId,gameVersion:version,region:z.string().nullable(),displayName:z.string(),description:z.string(),sha256,size:bytes.min(1).max(8*1024**3),publisher:z.string(),createdAt:z.string().or(z.date()),downloadUrl:z.string(),manifest:communitySaveManifestSchema}).strict())}).strict())}).strict();
function exactCatalog(catalog:z.infer<typeof masterCatalog>,gameTitleId:string,gameVersion:string){
  if(catalog.gameTitleId!==gameTitleId)throw new AppError('MASTER_METADATA_MISMATCH',502);
  for(const group of catalog.versions){if(group.gameVersion!==gameVersion)throw new AppError('MASTER_METADATA_MISMATCH',502);for(const item of group.saves){const manifest=item.manifest;if(item.gameTitleId!==gameTitleId||item.gameVersion!==gameVersion||item.downloadUrl!==`/api/v1/saves/${item.id}/archive`||manifest.platform!==item.platform||manifest.gameTitleId!==item.gameTitleId||manifest.saveTitleId!==item.saveTitleId||manifest.gameVersion!==item.gameVersion||manifest.archiveSha256!==item.sha256||manifest.archiveSize!==item.size||manifest.compatibility.gameVersion!==item.gameVersion)throw new AppError('MASTER_METADATA_MISMATCH',502);}}
  return catalog;
}
const part=(config:Config,id:string)=>path.join(config.DATA_DIR,'portable-saves','.staging',`${id}.part`),relative=(userId:string,id:string,digest:string)=>path.join('portable-saves',userId,`${id}-${digest}.ps5save`);
const view=(row:any)=>({id:row.id,origin:row.origin,consoleId:row.console_id,localUserId:row.local_user_id,platform:row.platform,gameTitleId:row.game_title_id,saveTitleId:row.save_title_id,directory:row.directory,gameVersion:row.game_version,region:row.region,state:row.state,totalBytes:row.total_bytes,uploadedBytes:row.uploaded_bytes,sha256:row.sha256,fileCount:row.file_count,manifest:row.manifest,displayName:row.display_name,description:row.description,masterPublicationId:row.master_publication_id,masterState:row.master_state,error:row.error,createdAt:row.created_at,updatedAt:row.updated_at,downloadUrl:row.state==='READY'?`/api/v1/portable-saves/${row.id}/download`:null});

export async function communitySaveRoutes(app:FastifyInstance,db:DB,config:Config,auth:Auth,logs:Logger,fetcher:Fetch=fetch){
  const masterCredentials=(userId:string)=>Promise.all([approvedMasterCredential(db,config),approvedMasterUserCredential(db,config,userId,fetcher)]);
  const currentTerms=async()=>{const value=masterTerms.parse(await masterRequest(config,'/api/v1/terms/current',{},fetcher));if(createHash('sha256').update(value.body).digest('hex')!==value.sha256)throw new AppError('INVALID_MASTER_RESPONSE',502);return value;};
  const consent=async(userId:string)=>{const current=await currentTerms(),accepted=(await db.query('SELECT terms_version,terms_sha256 FROM community_user_terms WHERE user_id=$1',[userId])).rows[0];if(!accepted||accepted.terms_version!==current.version||accepted.terms_sha256!==current.sha256)throw new AppError('TERMS_ACCEPTANCE_REQUIRED',428,'Review and accept the current Community Save terms.');return current;};
  const installedVersion=async(consoleId:string,userId:string,gameTitleId:string)=>{
    const rows=(await db.query(`SELECT DISTINCT r.version,r.kind FROM console_library_entries l JOIN consoles c ON c.id=l.console_id JOIN game_releases r ON r.id=l.release_id JOIN games g ON g.id=r.game_id WHERE c.id=$1 AND c.user_id=$2 AND g.title_id=$3 AND l.state='READY_ON_PS5' AND r.kind IN ('BASE','UPDATE')`,[consoleId,userId,gameTitleId])).rows as {version:string;kind:string}[];
    const candidates=rows.some(row=>row.kind==='UPDATE')?rows.filter(row=>row.kind==='UPDATE'):rows;if(!candidates.length)return null;
    const parts=(value:string)=>{const match=/^(\d+)\.(\d+)(?:\.(\d+))?$/.exec(value);return match?[Number(match[1]),Number(match[2]),Number(match[3]??0)]:null;};
    if(candidates.length>1&&candidates.some(row=>!parts(row.version)))return null;
    return candidates.sort((a,b)=>{const left=parts(a.version),right=parts(b.version);if(!left||!right)return 0;for(let i=0;i<3;i++)if(left[i]!==right[i])return right[i]!-left[i]!;return 0;})[0]!.version;
  };
  const requireInstalledVersion=async(consoleId:string,userId:string,gameTitleId:string,gameVersion:string)=>{if(await installedVersion(consoleId,userId,gameTitleId)!==gameVersion)throw new AppError('GAME_VERSION_MISMATCH',409);};

  app.get('/api/v1/community/terms',async req=>{const user=await auth.user(req),current=await currentTerms(),accepted=Boolean((await db.query('SELECT 1 FROM community_user_terms WHERE user_id=$1 AND terms_version=$2 AND terms_sha256=$3',[user.id,current.version,current.sha256])).rowCount);return {...current,accepted};});
  app.post('/api/v1/community/terms/accept',async req=>{const user=await auth.user(req),body=terms.parse(req.body),current=await currentTerms();if(body.termsVersion!==current.version||body.termsSha256!==current.sha256)throw new AppError('TERMS_CHANGED',409);await db.query(`INSERT INTO community_user_terms(user_id,terms_version,terms_sha256) VALUES($1,$2,$3) ON CONFLICT(user_id) DO UPDATE SET terms_version=$2,terms_sha256=$3,accepted_at=now()`,[user.id,current.version,current.sha256]);await logs.write('INFO','community.terms_accepted',`Community save terms accepted by ${user.username}`,{version:current.version});return {ok:true};});

  app.post('/api/v1/consoles/:id/saves/exports',async(req,reply)=>{const user=await auth.user(req),consoleId=uuid.parse((req.params as {id:string}).id),body=exportRequest.parse(req.body);
    const source=await consoleSaveData(db,user.id,consoleId,body.localUserId,body.platform,body.gameTitleId,body.saveTitleId,body.directory);if(!source)throw new AppError('NOT_FOUND',404);if(source.capabilities.saveExport!==true)throw new AppError('CAPABILITY_UNAVAILABLE',409,'This agent has not reported portable save export support.');if(presence(source.last_seen?new Date(source.last_seen).getTime():null)!=='ONLINE')throw new AppError('CONSOLE_OFFLINE',409);await requireInstalledVersion(consoleId,user.id,source.game_title_id,body.gameVersion);
    const id=randomUUID();await db.query(`INSERT INTO portable_save_archives(id,user_id,origin,console_id,local_user_id,platform,game_title_id,save_title_id,directory,game_version,region,source_modified_at,state) VALUES($1,$2,'EXPORT',$3,$4,$5,$6,$7,$8,$9,$10,$11,'REQUESTED')`,[id,user.id,consoleId,source.local_user_id,source.platform,source.game_title_id,source.save_title_id,source.directory,body.gameVersion,body.region??null,source.modified_at]);return reply.code(202).send({id,state:'REQUESTED'});
  });
  app.get('/api/v1/portable-saves',async req=>(await db.query('SELECT * FROM portable_save_archives WHERE user_id=$1 ORDER BY created_at DESC',[(await auth.user(req)).id])).rows.map(view));
  app.get('/api/v1/portable-saves/:id/download',async(req,reply)=>{const user=await auth.user(req),id=uuid.parse((req.params as {id:string}).id),row=(await db.query("SELECT * FROM portable_save_archives WHERE id=$1 AND user_id=$2 AND state='READY'",[id,user.id])).rows[0];if(!row)throw new AppError('NOT_FOUND',404);return serveStoredFile(req,reply,within(config.DATA_DIR,path.join(config.DATA_DIR,row.relative_path)),row.total_bytes,row.sha256,'application/vnd.ps5library.save');});
  app.get('/api/v1/device/save-exports',async req=>{const device=await auth.device(req),row=(await db.query("SELECT p.*,c.firmware,c.runtime FROM portable_save_archives p JOIN consoles c ON c.id=p.console_id WHERE p.console_id=$1 AND p.origin='EXPORT' AND p.state IN ('REQUESTED','UPLOADING','VERIFYING') ORDER BY p.created_at LIMIT 1",[device.id])).rows[0];return row?{...view(row),firmware:row.firmware,runtime:row.runtime}:null;});
  app.post('/api/v1/device/save-exports/:id/start',async req=>{const device=await auth.device(req),id=uuid.parse((req.params as {id:string}).id),body=start.parse(req.body);return transaction(db,async sql=>{const row=(await sql.query("SELECT * FROM portable_save_archives WHERE id=$1 AND console_id=$2 AND origin='EXPORT' AND state IN ('REQUESTED','UPLOADING') FOR UPDATE",[id,device.id])).rows[0];if(!row)throw new AppError('NOT_FOUND',404);const m=body.manifest;if(m.archiveSize!==body.totalBytes||m.archiveSha256!==body.sha256||m.platform!==row.platform||m.gameTitleId!==row.game_title_id||m.saveTitleId!==row.save_title_id||m.directory!==row.directory||m.gameVersion!==row.game_version)throw new AppError('METADATA_MISMATCH',409);
      if(row.total_bytes!==null&&(row.total_bytes!==body.totalBytes||row.sha256!==body.sha256))throw new AppError('METADATA_MISMATCH',409);if(row.total_bytes===null){if(quotaExceeded(await storageUsage(sql,{portableSaveId:id}),body.totalBytes,config.QUOTA_BYTES))throw new AppError('QUOTA_EXCEEDED',409);await requireDiskSpace(config.DATA_DIR,body.totalBytes+config.DISK_MARGIN_BYTES);}const uploaded=await resumeUpload(part(config,id),body.totalBytes);await sql.query("UPDATE portable_save_archives SET state='UPLOADING',total_bytes=$2,uploaded_bytes=$3,sha256=$4,file_count=$5,manifest=$6,error=NULL,updated_at=now() WHERE id=$1",[id,body.totalBytes,uploaded,body.sha256,m.fileCount,m]);return {uploadedBytes:uploaded};});});
  app.post('/api/v1/device/save-exports/:id/chunks',async req=>{const device=await auth.device(req),id=uuid.parse((req.params as {id:string}).id),body=uploadChunk.parse(req.body);return transaction(db,async sql=>{const row=(await sql.query("SELECT * FROM portable_save_archives WHERE id=$1 AND console_id=$2 AND state='UPLOADING' FOR UPDATE",[id,device.id])).rows[0];if(!row)throw new AppError('NOT_FOUND',404);const uploaded=await appendUpload(part(config,id),body.offset,body.data,row.total_bytes);await sql.query('UPDATE portable_save_archives SET uploaded_bytes=$2,updated_at=now() WHERE id=$1',[id,uploaded]);return {uploadedBytes:uploaded};});});
  app.post('/api/v1/device/save-exports/:id/complete',async req=>{const device=await auth.device(req),id=uuid.parse((req.params as {id:string}).id),row=await transaction(db,async sql=>{const found=(await sql.query("SELECT * FROM portable_save_archives WHERE id=$1 AND console_id=$2 AND state IN ('UPLOADING','VERIFYING') FOR UPDATE",[id,device.id])).rows[0];if(!found)throw new AppError('NOT_FOUND',404);if(found.uploaded_bytes!==found.total_bytes)throw new AppError('INCOMPLETE_INPUT',409);await sql.query("UPDATE portable_save_archives SET state='VERIFYING',updated_at=now() WHERE id=$1",[id]);return found;});const destination=within(config.DATA_DIR,path.join(config.DATA_DIR,relative(row.user_id,id,row.sha256))),staging=part(config,id),source=(await lstat(staging).catch(()=>null))?.isFile()?staging:destination;try{await validatePortableSaveArchive(source,row.total_bytes,row.file_count,row.sha256);}catch{await rm(staging,{force:true});await db.query("UPDATE portable_save_archives SET state='ERROR',error='CORRUPT_INPUT',updated_at=now() WHERE id=$1",[id]);throw new AppError('CORRUPT_INPUT',409);}if(source===staging){await mkdir(path.dirname(destination),{recursive:true});await rename(staging,destination);}await db.query("UPDATE portable_save_archives SET state='READY',relative_path=$2,error=NULL,updated_at=now() WHERE id=$1",[id,path.relative(config.DATA_DIR,destination)]);return {ok:true};});
  app.post('/api/v1/device/save-exports/:id/error',async req=>{const device=await auth.device(req),id=uuid.parse((req.params as {id:string}).id),body=failure.parse(req.body);if(!(await db.query("UPDATE portable_save_archives SET state='ERROR',error=$3,updated_at=now() WHERE id=$1 AND console_id=$2 AND state IN ('REQUESTED','UPLOADING','VERIFYING')",[id,device.id,body.error])).rowCount)throw new AppError('NOT_FOUND',404);await rm(part(config,id),{force:true});return {ok:true};});

  app.post('/api/v1/portable-saves/:id/publish',async(req,reply)=>{const user=await auth.user(req),id=uuid.parse((req.params as {id:string}).id),body=publication.parse(req.body);await consent(user.id);const [token,userToken]=await masterCredentials(user.id),row=(await db.query("SELECT * FROM portable_save_archives WHERE id=$1 AND user_id=$2 AND origin='EXPORT' AND state='READY'",[id,user.id])).rows[0];if(!row)throw new AppError('NOT_FOUND',404);let publicationId=row.master_publication_id as string|null;if(publicationId&&row.master_state!=='UPLOAD_ERROR')throw new AppError('ALREADY_PUBLISHED',409);if(!publicationId){const created=z.object({id:uuid,state:z.literal('PUBLISHING'),uploadUrl:z.string()}).parse(await masterRequest(config,'/api/v1/saves/publications',{method:'POST',token,userToken,body:{manifest:row.manifest,displayName:body.displayName,description:body.description}},fetcher));publicationId=created.id;await db.query("UPDATE portable_save_archives SET display_name=$2,description=$3,master_publication_id=$4,master_state='UPLOADING',updated_at=now() WHERE id=$1",[id,body.displayName,body.description,publicationId]);}const uploadUrl=new URL(`/api/v1/saves/publications/${publicationId}/archive`,config.COMMUNITY_MASTER_URL),file=within(config.DATA_DIR,path.join(config.DATA_DIR,row.relative_path)),checked=await regularFile(file,'r');try{if(checked.info.size!==row.total_bytes||await fileHandleHash(checked.handle)!==row.sha256)throw new AppError('CORRUPT_INPUT',409);const response=await fetcher(uploadUrl,{method:'PUT',redirect:'error',signal:AbortSignal.timeout(30*60_000),headers:{authorization:`Bearer ${token}`,'x-ps5library-user-token':userToken,'content-type':'application/vnd.ps5library.save','content-length':String(row.total_bytes)},body:checked.handle.createReadStream({start:0,autoClose:false}) as any,duplex:'half'} as any);if(!response.ok){await response.body?.cancel();throw new AppError('MASTER_UPLOAD_FAILED',502);}await response.body?.cancel();}catch(error){await db.query("UPDATE portable_save_archives SET master_state='UPLOAD_ERROR',updated_at=now() WHERE id=$1",[id]);throw error;}finally{await checked.handle.close();}await db.query("UPDATE portable_save_archives SET master_state='PUBLISHING',updated_at=now() WHERE id=$1",[id]);await logs.write('INFO','community.save_published',`Portable save submitted by ${user.username}`,{publicationId,titleId:row.game_title_id,version:row.game_version});return reply.code(202).send({publicationId,state:'PUBLISHING'});});

  app.get('/api/v1/community/saves',async req=>{const user=await auth.user(req),query=z.object({consoleId:uuid,gameTitleId:titleId,gameVersion:version}).parse(req.query);await consent(user.id);await requireInstalledVersion(query.consoleId,user.id,query.gameTitleId,query.gameVersion);const [token,userToken]=await masterCredentials(user.id),catalog=masterCatalog.parse(await masterRequest(config,`/api/v1/saves?gameTitleId=${encodeURIComponent(query.gameTitleId)}&gameVersion=${encodeURIComponent(query.gameVersion)}`,{token,userToken},fetcher));return exactCatalog(catalog,query.gameTitleId,query.gameVersion);});
  app.post('/api/v1/community/saves/:id/download',async(req,reply)=>{
    const user=await auth.user(req),publicationId=uuid.parse((req.params as {id:string}).id),body=z.object({consoleId:uuid,gameTitleId:titleId,gameVersion:version}).strict().parse(req.body);await consent(user.id);await requireInstalledVersion(body.consoleId,user.id,body.gameTitleId,body.gameVersion);
    const [token,userToken]=await masterCredentials(user.id),catalog=exactCatalog(masterCatalog.parse(await masterRequest(config,`/api/v1/saves?gameTitleId=${encodeURIComponent(body.gameTitleId)}&gameVersion=${encodeURIComponent(body.gameVersion)}`,{token,userToken},fetcher)),body.gameTitleId,body.gameVersion),item=catalog.versions.flatMap(group=>group.saves).find(value=>value.id===publicationId);if(!item)throw new AppError('NOT_FOUND',404);
    const id=randomUUID(),staging=part(config,id),destination=within(config.DATA_DIR,path.join(config.DATA_DIR,relative(user.id,id,item.sha256)));
    await transaction(db,async sql=>{if(quotaExceeded(await storageUsage(sql),item.size,config.QUOTA_BYTES))throw new AppError('QUOTA_EXCEEDED',409);await requireDiskSpace(config.DATA_DIR,item.size+config.DISK_MARGIN_BYTES);await sql.query(`INSERT INTO portable_save_archives(id,user_id,origin,platform,game_title_id,save_title_id,directory,game_version,region,state,total_bytes,sha256,file_count,manifest,display_name,description,master_publication_id,master_state) VALUES($1,$2,'COMMUNITY',$3,$4,$5,$6,$7,$8,'DOWNLOADING',$9,$10,$11,$12,$13,$14,$15,'PUBLISHED')`,[id,user.id,item.platform,item.gameTitleId,item.saveTitleId,item.manifest.directory,item.gameVersion,item.region,item.size,item.sha256,item.manifest.fileCount,item.manifest,item.displayName,item.description,item.id]);});
    let handle:FileHandle;try{await mkdir(path.dirname(staging),{recursive:true});handle=await open(staging,'wx',0o600);}catch{await db.query("UPDATE portable_save_archives SET state='ERROR',error='STAGING_FAILED',updated_at=now() WHERE id=$1",[id]);throw new AppError('STAGING_FAILED',500);}
    try{const response=await fetcher(new URL(`/api/v1/saves/${item.id}/archive`,config.COMMUNITY_MASTER_URL),{redirect:'error',signal:AbortSignal.timeout(30*60_000),headers:{authorization:`Bearer ${token}`,'x-ps5library-user-token':userToken,accept:'application/vnd.ps5library.save'}});if(!response.ok||!response.body)throw new Error('MASTER_DOWNLOAD_FAILED');let size=0;const digest=createHash('sha256');for await(const value of response.body){const data=Buffer.from(value);size+=data.length;if(size>item.size)throw new Error('ARCHIVE_SIZE_MISMATCH');digest.update(data);let offset=0;while(offset<data.length)offset+=(await handle.write(data,offset,data.length-offset,null)).bytesWritten;}await handle.sync();if(size!==item.size||digest.digest('hex')!==item.sha256)throw new Error('ARCHIVE_MISMATCH');}
    catch{await handle.close().catch(()=>{});await rm(staging,{force:true});await db.query("UPDATE portable_save_archives SET state='ERROR',error='MASTER_DOWNLOAD_FAILED',updated_at=now() WHERE id=$1",[id]);throw new AppError('MASTER_DOWNLOAD_FAILED',502);}await handle.close();
    try{await validatePortableSaveArchive(staging,item.size,item.manifest.fileCount,item.sha256);}catch{await rm(staging,{force:true});await db.query("UPDATE portable_save_archives SET state='ERROR',error='CORRUPT_INPUT',updated_at=now() WHERE id=$1",[id]);throw new AppError('CORRUPT_INPUT',409);}await mkdir(path.dirname(destination),{recursive:true});await rename(staging,destination);await db.query("UPDATE portable_save_archives SET state='READY',uploaded_bytes=total_bytes,relative_path=$2,error=NULL,updated_at=now() WHERE id=$1",[id,path.relative(config.DATA_DIR,destination)]);return reply.code(201).send({id,state:'READY'});
  });

  app.post('/api/v1/portable-saves/:id/import',async(req,reply)=>{const user=await auth.user(req),archiveId=uuid.parse((req.params as {id:string}).id),body=z.object({consoleId:uuid,localUserId}).strict().parse(req.body);const archive=(await db.query("SELECT * FROM portable_save_archives WHERE id=$1 AND user_id=$2 AND state='READY'",[archiveId,user.id])).rows[0];if(!archive)throw new AppError('NOT_FOUND',404);const target=await consoleSaveData(db,user.id,body.consoleId,body.localUserId,archive.platform,archive.game_title_id,archive.save_title_id,archive.directory);if(!target)throw new AppError('TARGET_SAVE_SLOT_REQUIRED',409,'Create the matching save slot in the game before importing.');if(target.capabilities.saveBackup!==true||target.capabilities.saveImport!==true||target.capabilities.saveRollback!==true)throw new AppError('CAPABILITY_UNAVAILABLE',409);if(presence(target.last_seen?new Date(target.last_seen).getTime():null)!=='ONLINE')throw new AppError('CONSOLE_OFFLINE',409);await requireInstalledVersion(body.consoleId,user.id,archive.game_title_id,archive.game_version);const backupId=randomUUID(),id=randomUUID();await transaction(db,async sql=>{await sql.query(`INSERT INTO save_backups(id,user_id,console_id,local_user_id,platform,game_title_id,save_title_id,directory,source_modified_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)`,[backupId,user.id,body.consoleId,body.localUserId,target.platform,target.game_title_id,target.save_title_id,target.directory,target.modified_at]);await sql.query(`INSERT INTO save_imports(id,user_id,archive_id,console_id,local_user_id,rollback_backup_id,state) VALUES($1,$2,$3,$4,$5,$6,'WAITING_ROLLBACK')`,[id,user.id,archiveId,body.consoleId,body.localUserId,backupId]);});return reply.code(202).send({id,state:'WAITING_ROLLBACK',rollbackBackupId:backupId});});
  app.get('/api/v1/save-imports',async req=>(await db.query(`SELECT i.*,p.display_name,p.game_title_id,p.game_version,p.save_title_id,p.directory,p.total_bytes,b.state AS rollback_state FROM save_imports i JOIN portable_save_archives p ON p.id=i.archive_id JOIN save_backups b ON b.id=i.rollback_backup_id WHERE i.user_id=$1 ORDER BY i.created_at DESC`,[(await auth.user(req)).id])).rows.map(row=>({id:row.id,archiveId:row.archive_id,consoleId:row.console_id,localUserId:row.local_user_id,rollbackBackupId:row.rollback_backup_id,state:row.state,rollbackState:row.rollback_state,displayName:row.display_name,gameTitleId:row.game_title_id,gameVersion:row.game_version,saveTitleId:row.save_title_id,directory:row.directory,downloadedBytes:row.downloaded_bytes,totalBytes:row.total_bytes,speedBytesPerSecond:row.speed_bytes_per_second,error:row.error,createdAt:row.created_at,updatedAt:row.updated_at})));
  app.get('/api/v1/device/save-imports',async req=>{const device=await auth.device(req);await db.query("UPDATE save_imports i SET state='ERROR',error='ROLLBACK_FAILED',updated_at=now() FROM save_backups b WHERE i.console_id=$1 AND i.rollback_backup_id=b.id AND i.state='WAITING_ROLLBACK' AND b.state='ERROR'",[device.id]);await db.query("UPDATE save_imports i SET state='REQUESTED',updated_at=now() FROM save_backups b WHERE i.console_id=$1 AND i.rollback_backup_id=b.id AND i.state='WAITING_ROLLBACK' AND b.state='READY'",[device.id]);const row=(await db.query(`SELECT i.*,p.platform,p.game_title_id,p.save_title_id,p.directory,p.game_version,p.total_bytes,p.sha256,p.file_count,p.manifest FROM save_imports i JOIN portable_save_archives p ON p.id=i.archive_id WHERE i.console_id=$1 AND i.state IN ('REQUESTED','IMPORTING','VERIFYING') ORDER BY i.created_at LIMIT 1`,[device.id])).rows[0];return row?{id:row.id,state:row.state,localUserId:row.local_user_id,platform:row.platform,gameTitleId:row.game_title_id,saveTitleId:row.save_title_id,directory:row.directory,gameVersion:row.game_version,totalBytes:row.total_bytes,sha256:row.sha256,fileCount:row.file_count,manifest:row.manifest,archiveUrl:`/api/v1/device/save-imports/${row.id}/archive`}:null;});
  app.post('/api/v1/device/save-imports/:id/start',async req=>{const device=await auth.device(req),id=uuid.parse((req.params as {id:string}).id);if(!(await db.query("UPDATE save_imports SET state='IMPORTING',error=NULL,updated_at=now() WHERE id=$1 AND console_id=$2 AND state IN ('REQUESTED','IMPORTING')",[id,device.id])).rowCount)throw new AppError('NOT_FOUND',404);return {ok:true};});
  app.post('/api/v1/device/save-imports/:id/progress',async req=>{const device=await auth.device(req),id=uuid.parse((req.params as {id:string}).id),body=importProgress.parse(req.body);const changed=await db.query(`UPDATE save_imports i SET downloaded_bytes=$3,speed_bytes_per_second=$4,updated_at=now() FROM portable_save_archives p WHERE i.id=$1 AND i.console_id=$2 AND i.archive_id=p.id AND i.state IN ('REQUESTED','IMPORTING') AND $3 BETWEEN i.downloaded_bytes AND p.total_bytes`,[id,device.id,body.downloadedBytes,body.speedBytesPerSecond]);if(!changed.rowCount)throw new AppError('NOT_FOUND',404);return {ok:true};});
  app.get('/api/v1/device/save-imports/:id/archive',async(req,reply)=>{const device=await auth.device(req),id=uuid.parse((req.params as {id:string}).id),row=(await db.query(`SELECT p.* FROM save_imports i JOIN portable_save_archives p ON p.id=i.archive_id WHERE i.id=$1 AND i.console_id=$2 AND i.state IN ('REQUESTED','IMPORTING','VERIFYING') AND p.state='READY'`,[id,device.id])).rows[0];if(!row)throw new AppError('NOT_FOUND',404);return serveStoredFile(req,reply,within(config.DATA_DIR,path.join(config.DATA_DIR,row.relative_path)),row.total_bytes,row.sha256,'application/vnd.ps5library.save');});
  app.post('/api/v1/device/save-imports/:id/complete',async req=>{const device=await auth.device(req),id=uuid.parse((req.params as {id:string}).id);if(!(await db.query("UPDATE save_imports i SET state='COMPLETED',downloaded_bytes=p.total_bytes,speed_bytes_per_second=0,error=NULL,updated_at=now() FROM portable_save_archives p WHERE i.id=$1 AND i.console_id=$2 AND i.archive_id=p.id AND i.state IN ('IMPORTING','VERIFYING')",[id,device.id])).rowCount)throw new AppError('NOT_FOUND',404);return {ok:true};});
  app.post('/api/v1/device/save-imports/:id/error',async req=>{const device=await auth.device(req),id=uuid.parse((req.params as {id:string}).id),body=failure.parse(req.body);if(!(await db.query("UPDATE save_imports SET state='ERROR',error=$3,updated_at=now() WHERE id=$1 AND console_id=$2 AND state IN ('REQUESTED','IMPORTING','VERIFYING')",[id,device.id,body.error])).rowCount)throw new AppError('NOT_FOUND',404);return {ok:true};});
}
