#include "../agent/cheats.hpp"
#include "../agent/local.hpp"
#include "../common/client.hpp"
#include <algorithm>
#include <cassert>
#include <map>
#include <openssl/evp.h>

using namespace ps5library;
namespace {
class Memory final:public CheatRuntime {
public:
  std::optional<CheatTarget> target;
  std::map<std::uint64_t,unsigned char> bytes;
  int failAfter=-1,writes=0;bool readable=true,writable=true;
  std::optional<CheatTarget> running(std::string_view={})override{return target;}
  bool canRead()const override{return readable;}
  bool canWrite()const override{return writable;}
  std::vector<unsigned char> read(const CheatTarget& observed,std::uint64_t address,std::size_t size)override{if(!target||observed.token!=target->token)throw std::runtime_error("PROCESS_EXITED");std::vector<unsigned char> value;for(std::size_t i=0;i<size;i++)value.push_back(bytes[address+i]);return value;}
  void write(const CheatTarget& observed,std::uint64_t address,const std::vector<unsigned char>& value)override{if(!target||observed.token!=target->token)throw std::runtime_error("PROCESS_EXITED");if(failAfter>=0&&writes++>=failAfter){failAfter=-1;throw std::runtime_error("WRITE_FAILED");}for(std::size_t i=0;i<value.size();i++)bytes[address+i]=value[i];}
};
std::string base64(const std::string& value){std::string result(4*((value.size()+2)/3),'\0');auto size=EVP_EncodeBlock(reinterpret_cast<unsigned char*>(result.data()),reinterpret_cast<const unsigned char*>(value.data()),static_cast<int>(value.size()));result.resize(static_cast<std::size_t>(size));return result;}
std::string profile(const std::string& off="aabb"){return std::string(R"({"name":"Fixture","id":"PPSA01628","version":"1.026.000","process":"eboot.bin","mods":[{"name":"Infinite health","description":"Host fixture","type":"checkbox","memory":[{"offset":"10","on":"9090","off":")")+off+R"("},{"offset":"20","on":"cccc","off":"1122"}]}]})";}
CheatProfile approved(const fs::path& file){auto parsed=parseCheatProfile(file);parsed.localApproved=true;return parsed;}
}

int main(){
  const auto session=std::string(64,'c');const std::string auth="\r\nAuthorization: Bearer "+std::string(localAgentCredential)+"\r\n\r\n";auto listRequest=parseLocalAgentRequest("GET /api/v1/agent/cheats HTTP/1.1"+auth);assert(listRequest.action==LocalAgentAction::Cheats);const auto profileId=std::string(64,'a'),entryId=std::string(64,'b');const auto cheatHeaders="\r\nAuthorization: Bearer "+std::string(localAgentCredential)+"\r\nX-PS5Library-Cheat-Session: "+session+"\r\nX-PS5Library-Cheat-Approval: "+profileId+"\r\n\r\n";auto enableRequest=parseLocalAgentRequest("POST /api/v1/agent/cheats/"+profileId+"/"+entryId+"/enable HTTP/1.1"+cheatHeaders,session);assert(enableRequest.action==LocalAgentAction::CheatEnable&&enableRequest.profileId==profileId&&enableRequest.entryId==entryId&&enableRequest.explicitApproval);assert(parseLocalAgentRequest("POST /api/v1/agent/cheats/"+profileId+"/"+entryId+"/enable HTTP/1.1"+auth,session).action==LocalAgentAction::Invalid);const auto shellToken=std::string(64,'d'),shellHeaders="\r\nAuthorization: Bearer "+shellToken+"\r\n\r\n";assert(parseLocalAgentRequest("POST /api/v1/agent/cheats/"+profileId+"/"+entryId+"/disable HTTP/1.1"+shellHeaders,{},shellToken,true).action==LocalAgentAction::CheatDisable);assert(parseLocalAgentRequest("GET /api/v1/agent/cheats HTTP/1.1"+shellHeaders,{},shellToken,true).action==LocalAgentAction::Invalid);assert(parseLocalAgentRequest("POST /api/v1/agent/cheats/"+profileId+"/"+entryId+"/disable HTTP/1.1"+auth,{},shellToken,true).action==LocalAgentAction::Invalid);auto failed=localAgentFailure(enableRequest,"LOCAL_APPROVAL_REQUIRED");assert(failed["state"].string()=="ERROR"&&failed["requestedEnabled"].boolean()&&failed["approvalRequired"].boolean()&&failed["changedAtUnixMs"].number()>0&&failed["profileId"].string()==profileId&&failed["entryId"].string()==entryId);assert(parseLocalAgentRequest("POST /api/v1/agent/cheats/1234/20/enable HTTP/1.1"+cheatHeaders,session).action==LocalAgentAction::Invalid);assert(parseLocalAgentRequest("POST /api/v1/agent/cheats/"+profileId+"/"+entryId+"/write/7fff HTTP/1.1"+cheatHeaders,session).action==LocalAgentAction::Invalid);
  const auto root=fs::temp_directory_path()/("ps5library-cheats-"+randomHex(8));fs::create_directories(root/"inbox");atomicBytes(root/"inbox/PPSA01628_1.026.000_eboot.bin.json",profile());auto parsed=approved(root/"inbox/PPSA01628_1.026.000_eboot.bin.json");assert(parsed.titleId=="PPSA01628"&&parsed.version=="1.026.000"&&parsed.process=="eboot.bin"&&parsed.entries.size()==1&&parsed.entries[0].patches.size()==2);auto inventory=Json::array();inventory.add(Json::object({{"titleId","PPSA01628"},{"version","1.026.000"},{"contentId","UP0001-PPSA01628_00-EXAMPLE000000000"},{"available",true}}));CheatService manualService(root);bool rejected=false;try{manualService.enable(parsed.id,parsed.entries[0].id,inventory,Json::array());}catch(const std::exception& error){rejected=std::string(error.what())=="LOCAL_APPROVAL_REQUIRED";}assert(rejected&&!fs::exists(root/"approvals"/(parsed.id+".json")));rejected=false;try{manualService.enable(parsed.id,parsed.entries[0].id,inventory,Json::array(),true);}catch(const std::exception& error){rejected=std::string(error.what())=="CHEAT_RUNTIME_UNVERIFIED";}assert(rejected&&fs::is_regular_file(root/"approvals"/(parsed.id+".json")));
  Memory memory;memory.target=CheatTarget{7,-1,0,0,0x1000,0x100,"PPSA01628","1.026.000","eboot.bin","UP0001-PPSA01628_00-EXAMPLE000000000","a"+std::string(63,'0'),{}};memory.bytes[0x10]=0xaa;memory.bytes[0x11]=0xbb;memory.bytes[0x20]=0x11;memory.bytes[0x21]=0x22;CheatEngine engine(memory,root/"journal");auto entry=parsed.entries[0].id;auto enabled=engine.enable(parsed,entry);assert(enabled["enabled"].boolean()&&enabled["state"].string()=="ENABLED"&&enabled["changedAtUnixMs"].number()>0);assert(memory.bytes[0x10]==0x90&&memory.bytes[0x11]==0x90&&memory.bytes[0x20]==0xcc&&engine.enabled(parsed.id,entry));auto disabled=engine.disable(parsed.id,entry);assert(!disabled["enabled"].boolean()&&disabled["state"].string()=="DISABLED"&&disabled["changedAtUnixMs"].number()>0);assert(memory.bytes[0x10]==0xaa&&memory.bytes[0x11]==0xbb&&memory.bytes[0x20]==0x11&&!engine.enabled(parsed.id,entry));
  memory.bytes[0x10]=0xff;rejected=false;try{engine.enable(parsed,entry);}catch(const std::exception& error){rejected=std::string(error.what())=="CHEAT_PREIMAGE_MISMATCH";}assert(rejected&&!engine.enabled(parsed.id,entry));memory.bytes[0x10]=0xaa;
  memory.failAfter=1;memory.writes=0;rejected=false;try{engine.enable(parsed,entry);}catch(...){rejected=true;}assert(rejected&&memory.bytes[0x10]==0xaa&&memory.bytes[0x11]==0xbb&&!engine.enabled(parsed.id,entry));memory.failAfter=-1;
  memory.readable=false;rejected=false;try{engine.enable(parsed,entry);}catch(const std::exception& error){rejected=std::string(error.what())=="CHEAT_RUNTIME_UNVERIFIED";}assert(rejected&&!engine.enabled(parsed.id,entry));memory.readable=true;
  memory.target->moduleSize=0x20;rejected=false;try{engine.enable(parsed,entry);}catch(const std::exception& error){rejected=std::string(error.what())=="CHEAT_PATCH_OUT_OF_BOUNDS";}assert(rejected&&!engine.enabled(parsed.id,entry));memory.target->moduleSize=0x100;
  assert(engine.enable(parsed,entry)["enabled"].boolean());memory.target.reset();engine.reconcile();assert(!engine.enabled(parsed.id,entry));
  atomicBytes(root/"inbox/PPSA01628_1.026.000_bad.json",std::string(R"({"name":"Fixture","id":"PPSA01628","version":"1.026.000","process":"bad","mods":[{"name":"Absolute","type":"checkbox","memory":[{"offset":"10","on":"90","off":"cc","absolute":true}]}]})"));rejected=false;try{parseCheatProfile(root/"inbox/PPSA01628_1.026.000_bad.json");}catch(...){rejected=true;}assert(rejected);
  CheatService service(root);auto deliveryBody=profile(),hash=fileHash(root/"inbox/PPSA01628_1.026.000_eboot.bin.json");auto delivery=Json::object({{"action","PLACE"},{"id","11111111-1111-4111-8111-111111111111"},{"profileId","22222222-2222-4222-8222-222222222222"},{"profileSha256",hash},{"fileName","PPSA01628_1.026.000_eboot.bin.json"},{"titleId","PPSA01628"},{"gameVersion","1.026.000"},{"process","eboot.bin"},{"contentId","UP0001-PPSA01628_00-EXAMPLE000000000"},{"targetExecutableSha256",std::string(64,'a')},{"format","JSON"},{"profileBase64",base64(deliveryBody)}});assert(service.stage(delivery)==hash);auto listed=service.list(inventory,Json::array());assert(listed.size()>=1);bool saw=false;for(std::size_t i=0;i<listed.size();i++)if(listed[i]["id"].string()==hash){saw=true;assert(listed[i]["validation"].string()=="VALID"&&listed[i]["trust"].string()=="SERVER_APPROVED_HASH_DECLARED"&&!listed[i]["entries"][size_t(0)]["enabled"].boolean());}assert(saw);
  auto remove=Json::object({{"action","DELETE"},{"id",delivery["id"]},{"profileId",delivery["profileId"]},{"profileSha256",hash}});service.remove(remove);assert(fs::exists(root/"inbox/PPSA01628_1.026.000_eboot.bin.json")&&fs::exists(root/"approvals"/(hash+".json")));
  fs::remove(root/"inbox/PPSA01628_1.026.000_eboot.bin.json");service.stage(delivery);service.remove(remove);assert(!fs::exists(root/"inbox/PPSA01628_1.026.000_eboot.bin.json"));
  fs::remove_all(root);return 0;
}
