#include "../common/client.hpp"
#include <cassert>
#include <array>
#include <atomic>
#include <thread>
#include <chrono>
#include <cstring>
#include <poll.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <unistd.h>
struct PackageInfo {char id[48];int type,platform;};
struct MetaInfo {const char *uri,*extra,*scenario,*id,*name,*icon;};
struct PlayGoInfo {char languages[30][8],scenarios[64][3],ids[64][48];unsigned char reserved[6480];};
struct InstallError {int32_t code,version;char description[512],type[9];};
struct InstallStatus {char status[16],source[8];uint32_t remaining;uint64_t downloaded,initial,total;uint32_t promote;InstallError error;int32_t copyPercent;bool copyOnly;};
static std::atomic<int> initialized{0},moveStateDelayMs{0};static int requests=0,result=0,statusResult=0,statusRequests=0,uninstallRequests=0,existsRequests=0,moveRequests=0,moveCancels=0,moveSource=0,moveRequestSource=0,moveRequestResult=0,moveState=0,installLocation=1,installLocationGets=0,expectedInstallLocation=-1;static std::vector<int> installLocationSets;static std::string uninstalled,movedTitle;static std::array<char,12> movedTitleSlot{};static InstallStatus reported{};
static void sendAll(int fd,const char* data,size_t size){while(size){auto n=send(fd,data,size,0);assert(n>0);data+=n;size-=static_cast<size_t>(n);}}
static void serve(int listener,const std::string& payload,std::atomic<bool>& stop,std::atomic<int>& ranges,std::atomic<int>& reports,std::atomic<int>& relayFetches){
  while(!stop){pollfd ready{listener,POLLIN,0};if(poll(&ready,1,100)<=0)continue;int client=accept(listener,nullptr,nullptr);if(client<0)continue;
    std::string request;char buffer[4096];while(request.find("\r\n\r\n")==std::string::npos&&request.size()<16384){auto n=recv(client,buffer,sizeof(buffer),0);if(n<=0)break;request.append(buffer,static_cast<size_t>(n));}
    if(request.rfind("GET /api/v1/file ",0)==0){
      auto at=request.find("Range: bytes=");assert(at!=std::string::npos);at+=13;auto dash=request.find('-',at),end=request.find("\r\n",dash);assert(dash!=std::string::npos&&end!=std::string::npos);
      auto first=std::stoull(request.substr(at,dash-at)),last=std::stoull(request.substr(dash+1,end-dash-1));assert(first<=last&&last<payload.size());ranges++;
      auto header="HTTP/1.1 206 Partial Content\r\nContent-Type: application/octet-stream\r\nContent-Length: "+std::to_string(last-first+1)+"\r\nConnection: close\r\n\r\n";
      sendAll(client,header.data(),header.size());sendAll(client,payload.data()+first,last-first+1);
    }else if(request.find("/api/v1/native-downloads/")!=std::string::npos){
      relayFetches++;assert(request.find("Authorization: Bearer relay-credential\r\n")!=std::string::npos);const bool head=request.rfind("HEAD ",0)==0;size_t first=0,last=payload.size()-1;auto at=request.find("Range: bytes=");if(at!=std::string::npos){at+=13;auto dash=request.find('-',at),end=request.find("\r\n",dash);assert(dash!=std::string::npos&&end!=std::string::npos);first=std::stoull(request.substr(at,dash-at));if(end>dash+1)last=std::stoull(request.substr(dash+1,end-dash-1));assert(first<=last&&last<payload.size());}
      const bool partial=at!=std::string::npos;auto header="HTTP/1.1 "+std::string(partial?"206 Partial Content":"200 OK")+"\r\nContent-Type: application/octet-stream\r\nContent-Length: "+std::to_string(last-first+1)+"\r\nAccept-Ranges: bytes\r\nETag: \""+std::string(64,'a')+"\"\r\n"+(partial?"Content-Range: bytes "+std::to_string(first)+"-"+std::to_string(last)+"/"+std::to_string(payload.size())+"\r\n":"")+"Connection: close\r\n\r\n";sendAll(client,header.data(),header.size());if(!head)sendAll(client,payload.data()+first,last-first+1);
    }else if(request.find("/api/v1/ping ")!=std::string::npos){constexpr char response[]="HTTP/1.1 200 OK\r\nContent-Type: application/json\r\nContent-Length: 2\r\nConnection: close\r\n\r\n{}";sendAll(client,response,sizeof(response)-1);
    }else{assert(request.rfind("POST /api/v1/progress ",0)==0);reports++;constexpr char response[]="HTTP/1.1 200 OK\r\nContent-Type: application/json\r\nContent-Length: 2\r\nConnection: close\r\n\r\n{}";sendAll(client,response,sizeof(response)-1);}
    close(client);
  }
}
static std::string relayRequest(const std::string& url,const std::string& method="GET",const std::string& headers={}){
  const std::string prefix="http://127.0.0.1:";assert(url.rfind(prefix,0)==0);auto slash=url.find('/',prefix.size());auto port=std::stoi(url.substr(prefix.size(),slash-prefix.size()));int client=socket(AF_INET,SOCK_STREAM,0);assert(client>=0);sockaddr_in address{};address.sin_family=AF_INET;address.sin_addr.s_addr=htonl(INADDR_LOOPBACK);address.sin_port=htons(static_cast<uint16_t>(port));assert(connect(client,reinterpret_cast<sockaddr*>(&address),sizeof(address))==0);auto request=method+" "+url.substr(slash)+" HTTP/1.1\r\nHost: 127.0.0.1\r\n"+headers+"Connection: close\r\n\r\n";sendAll(client,request.data(),request.size());std::string response;char bytes[4096];for(;;){auto count=recv(client,bytes,sizeof(bytes),0);if(count<=0)break;response.append(bytes,static_cast<size_t>(count));}close(client);return response;
}
extern "C" int sceAppInstUtilInitialize(){initialized++;std::this_thread::sleep_for(std::chrono::milliseconds(40));return 0;}
extern "C" int sceAppInstUtilInstallByPackage(MetaInfo* meta,PackageInfo* info,PlayGoInfo* playgo){
  requests++;if(expectedInstallLocation>=0)assert(installLocation==expectedInstallLocation);if(std::string(meta->name)=="OpenStory"){assert(std::string(meta->id)=="UP9000-PPSA99783_00-OPENSTORYPS50000");assert(std::string(meta->uri)=="https://configured.example/api/v1/native-updates/PPSA99783/20/packages/"+std::string(64,'b')+".pkg");assert(std::string(meta->icon)=="https://configured.example/api/v1/native-updates/PPSA99783/icon.png");std::strncpy(info->id,"UP9000-PPSA99783_00-OPENSTORYPS50000",47);}else{assert(std::string(meta->id)=="IV0000-PPSA99991_00-PS5LIBRARYTEST01");assert(std::string(meta->uri)=="https://configured.example/api/v1/native-downloads/job/token/game.pkg");assert(std::string(meta->name)=="Owned homebrew");assert(std::string(meta->icon)=="https://configured.example/api/v1/native-downloads/job/icon-token/icon.png");std::strncpy(info->id,"IV0000-PPSA99991_00-PS5LIBRARYTEST01",47);}assert(playgo->reserved[6479]==0);return result;
}
extern "C" int sceAppInstUtilGetInstallStatus(const char* id,InstallStatus* status){
  statusRequests++;assert(std::string(id)=="IV0000-PPSA99991_00-PS5LIBRARYTEST01");*status=reported;return statusResult;
}
extern "C" int sceAppInstUtilAppUnInstall(const char* id){uninstallRequests++;uninstalled=id;return 0;}
extern "C" int testAppExists(const char* id,unsigned char* exists){existsRequests++;assert(std::string(id)=="PPSA99991"&&*exists==0);*exists=1;return 0;}
extern "C" int testGetStorage(const char* id,int* storage){assert(std::string(id)=="IV0000-PPSA99991_00-PS5LIBRARYTEST01");*storage=moveSource+1;return 0;}
extern "C" int testRequestMove(int source,const char* ids,size_t count){moveRequests++;moveRequestSource=source;std::memcpy(movedTitleSlot.data(),ids,movedTitleSlot.size());movedTitle=ids;assert(count==1);return moveRequestResult;}
extern "C" int testGetMoveProgress(void* raw){std::this_thread::sleep_for(std::chrono::milliseconds(moveStateDelayMs.load()));std::memset(raw,0,0x150);std::memcpy(raw,&moveState,sizeof(moveState));return 0;}
extern "C" int testCancelMove(){moveCancels++;return 0;}
extern "C" int testRegGet(int key,int* value){assert(key==0x02880300);installLocationGets++;*value=installLocation;return 0;}
extern "C" int testRegSet(int key,int value){assert(key==0x02880300);installLocationSets.push_back(value);installLocation=value;return 0;}
extern "C" void* __wrap_dlopen(const char* path,int){
  if(std::strstr(path,"SceRegMgr"))return !std::strcmp(path,"libSceRegMgr.sprx")?reinterpret_cast<void*>(1):nullptr;
  return reinterpret_cast<void*>(1);
}
extern "C" void* __wrap_dlsym(void*,const char* name){
  if(!std::strcmp(name,"sceAppInstUtilAppExists"))return reinterpret_cast<void*>(&testAppExists);
  if(!std::strcmp(name,"sceAppInstUtilAppGetStorageDestType"))return reinterpret_cast<void*>(&testGetStorage);
  if(!std::strcmp(name,"sceAppInstUtilAppRequestMoveApps"))return reinterpret_cast<void*>(&testRequestMove);
  if(!std::strcmp(name,"sceAppInstUtilGetAppMoveProgressInfo"))return reinterpret_cast<void*>(&testGetMoveProgress);
  if(!std::strcmp(name,"sceAppInstUtilAppCancelMoveApps"))return reinterpret_cast<void*>(&testCancelMove);
  if(!std::strcmp(name,"sceRegMgrGetInt"))return reinterpret_cast<void*>(&testRegGet);
  if(!std::strcmp(name,"sceRegMgrSetInt"))return reinterpret_cast<void*>(&testRegSet);
  return nullptr;
}
int main(){using namespace ps5library;
  assert(!nativeDownloadsAvailable());for(int i=0;i<100&&initialized.load()!=1;i++)std::this_thread::sleep_for(std::chrono::milliseconds(2));assert(initialized==1);assert(!nativeApiMutex().try_lock());for(int i=0;i<200&&!nativeDownloadsAvailable();i++)std::this_thread::sleep_for(std::chrono::milliseconds(2));assert(nativeDownloadsAvailable());assert(nativeMovesAvailable());
  const std::string url="https://configured.example/api/v1/native-downloads/job/token/game.pkg",icon="https://configured.example/api/v1/native-downloads/job/icon-token/icon.png",id="IV0000-PPSA99991_00-PS5LIBRARYTEST01";
  startNativeDownload(url,id,"Owned homebrew",icon);assert(requests==1&&installLocationGets==0&&installLocationSets.empty()&&installLocation==1);
  std::strncpy(reported.status,"downloading",sizeof(reported.status)-1);reported.remaining=12;reported.downloaded=345;reported.total=1000;reported.promote=4;reported.copyPercent=7;
  auto status=nativeDownloadStatus(id);assert(status["available"].boolean()&&status["status"].string()=="downloading"&&status["downloadedBytes"].number()==345&&status["totalBytes"].number()==1000&&status["remainingSeconds"].number()==12&&status["promoteProgress"].number()==4&&status["localCopyPercent"].number()==7&&statusRequests==1);
  reported.error.code=-77;status=nativeDownloadStatus(id);assert(status["errorCode"].number()==-77);reported.error.code=0;
  statusResult=-9;status=nativeDownloadStatus(id);assert(!status["available"].boolean()&&status["result"].number()==-9);statusResult=0;
  result=-7;bool rejected=false;try{startNativeDownload(url,id,"Owned homebrew",icon);}catch(const std::exception& e){rejected=std::string(e.what()).rfind("NATIVE_INSTALL_REJECTED_",0)==0;}assert(rejected);
  rejected=false;try{startNativeDownload(url,"IV0000-NPXS99991_00-PS5LIBRARYTEST01","Owned homebrew",icon);}catch(...){rejected=true;}assert(rejected&&requests==2);
  auto submissionRoot=fs::temp_directory_path()/randomHex(8),marker=submissionRoot/"native.json";const std::string submissionHash(64,'a');
  rejected=false;try{submitNativeDownload(marker,submissionHash,"https://configured.example","console-1",url,id,"Owned homebrew",icon);}catch(const NativeSubmissionRejected&){rejected=true;}assert(rejected&&!fs::exists(marker));
  result=0;submitNativeDownload(marker,submissionHash,"https://configured.example","console-1",url,id,"Owned homebrew",icon);assert(inspectNativeSubmission(marker,submissionHash,"https://configured.example","console-1",false)==NativeSubmissionDecision::Monitor);resetNativeSubmission(marker);
  auto targeted=submissionRoot/"usb.json";installLocation=2;installLocationGets=0;installLocationSets.clear();expectedInstallLocation=1;submitNativeDownload(targeted,submissionHash,"https://configured.example","console-1",url,id,"Owned homebrew",icon,1);expectedInstallLocation=-1;auto targetedState=readJson(targeted);assert(targetedState["state"].string()=="ACCEPTED"&&targetedState["installLocationPrevious"].number()==2&&targetedState["installLocationDesired"].number()==1&&!targetedState["installLocationRestored"].boolean()&&installLocation==1&&installLocationGets==2&&installLocationSets==std::vector<int>({1}));restoreNativeInstallTarget(targeted);targetedState=readJson(targeted);assert(targetedState["installLocationRestored"].boolean()&&installLocation==2&&installLocationGets==4&&installLocationSets==std::vector<int>({1,2}));resetNativeSubmission(targeted);assert(!fs::exists(targeted));
  targeted=submissionRoot/"internal.json";installLocation=1;installLocationGets=0;installLocationSets.clear();expectedInstallLocation=1;submitNativeDownload(targeted,submissionHash,"https://configured.example","console-1",url,id,"Owned homebrew",icon,0);expectedInstallLocation=-1;targetedState=readJson(targeted);assert(targetedState["installLocationDesired"].number()==1&&installLocation==1&&installLocationGets==1&&installLocationSets.empty());restoreNativeInstallTarget(targeted);resetNativeSubmission(targeted);
  targeted=submissionRoot/"m2.json";installLocation=1;installLocationGets=0;installLocationSets.clear();expectedInstallLocation=2;submitNativeDownload(targeted,submissionHash,"https://configured.example","console-1",url,id,"Owned homebrew",icon,2);expectedInstallLocation=-1;targetedState=readJson(targeted);assert(targetedState["installLocationDesired"].number()==2&&installLocation==2&&installLocationSets==std::vector<int>({2}));restoreNativeInstallTarget(targeted);assert(installLocation==1&&installLocationSets==std::vector<int>({2,1}));resetNativeSubmission(targeted);fs::remove_all(submissionRoot);
  auto update=Json::object({{"releaseKind","UPDATE"},{"titleId","PPSA99991"},{"contentId",id},{"baseContentVersion","01.002.003"},{"version","01.003.000"}}),installed=Json::object({{"titleId","PPSA99991"},{"contentId",id},{"contentVersion","01.002.003"}});assert(!validateNativeUpdateBase(update,installed,2,2));installed.set("contentVersion","01.003.000");assert(validateNativeUpdateBase(update,installed,2,2));installed.set("contentVersion","01.002.003");rejected=false;try{update.set("baseContentVersion","1.2.3");validateNativeUpdateBase(update,installed,2,2);}catch(...){rejected=true;}assert(rejected);update.set("baseContentVersion","01.002.003");installed.set("contentVersion","01.002.002");rejected=false;try{validateNativeUpdateBase(update,installed,2,2);}catch(const std::exception& error){rejected=std::string(error.what())=="NATIVE_UPDATE_BASE_MISMATCH";}assert(rejected);installed.set("contentVersion","01.002.003");rejected=false;try{validateNativeUpdateBase(update,installed,1,2);}catch(const std::exception& error){rejected=std::string(error.what())=="NATIVE_UPDATE_STORAGE_MISMATCH";}assert(rejected);
  uninstallNativeTitle("PPSA99991");assert(uninstallRequests==1&&uninstalled=="PPSA99991");
  rejected=false;try{uninstallNativeTitle("../PPSA99991");}catch(...){rejected=true;}assert(rejected&&uninstallRequests==1);
  assert(nativeMoveStorageType("/user","","")==0&&nativeMoveStorageType("/mnt/ext0","/dev/da1p1.crypt","ufs")==1&&nativeMoveStorageType("/mnt/ext1","/dev/ssd1.user","bfs")==2);
  assert(nativeMoveStorageType("/mnt/usb0","/dev/da1p1","exfatfs")==-1&&nativeMoveStorageType("/mnt/ext0","/dev/da1p1","bfs")==-1&&nativeMoveStorageType("/mnt/ext0","/dev/da1p1.crypt","exfatfs")==-1&&nativeMoveStorageType("/mnt/ext1","/dev/da1p1","bfs")==-1);
  auto moveVolumes=Json::array();moveVolumes.add(Json::object({{"storageId","internal-installed"},{"path","/user"},{"nativeMoveStorageType",int64_t(0)}}));moveVolumes.add(Json::object({{"storageId","ext0"},{"path","/mnt/ext0"},{"nativeMoveStorageType",int64_t(1)}}));moveVolumes.add(Json::object({{"storageId","ext1"},{"path","/mnt/ext1"},{"nativeMoveStorageType",int64_t(2)}}));moveVolumes.add(Json::object({{"storageId","usb0"},{"path","/mnt/usb0"},{"nativeMoveStorageType",int64_t(-1)}}));
  assert(nativeTitleStorageType("PPSA99991",id)==0);moveState=2;assert(nativeMoveState()==2);moveState=0;existsRequests=0;
  assert(nativeMoveTargetAvailable(moveVolumes,0)&&nativeMoveTargetAvailable(moveVolumes,1)&&!nativeMoveTargetAvailable(moveVolumes,2));auto rawOnly=Json::array();rawOnly.add(moveVolumes[size_t(0)]);rawOnly.add(moveVolumes[size_t(3)]);assert(!nativeMoveTargetAvailable(rawOnly,0));
  auto playGoTestRoot=fs::temp_directory_path()/randomHex(8),playGoRoot=playGoTestRoot/"playgo",playGoBackup=playGoTestRoot/"backup",playGo=playGoRoot/id/"00";fs::create_directories(playGo/"config"/id);atomicBytes(playGo/"d0.pdb","database zero");atomicBytes(playGo/"d1.pdb","database one");atomicBytes(playGo/"f0.pdb",{});atomicBytes(playGo/"app.si","PK\x03\x04 supplement");const auto playGoHash=fileHash(playGo/"d0.pdb");
  moveSource=0;nativeMoveTitle("PPSA99991",id,0,1,playGoBackup,playGoRoot);assert((existsRequests==1&&moveRequests==1&&moveRequestSource==0&&movedTitle=="PPSA99991"&&movedTitleSlot==std::array<char,12>{'P','P','S','A','9','9','9','9','1','\0','\0','\0'}));assert(fs::is_regular_file(playGoBackup/id/"00/d0.pdb")&&fileHash(playGoBackup/id/"00/d0.pdb")==fileHash(playGo/"d0.pdb"));
  fs::remove_all(playGo);moveSource=1;moveState=2;reconcileNativeMovePlayGo(playGoBackup,playGoRoot);assert(!fs::exists(playGo));moveState=0;reconcileNativeMovePlayGo(playGoBackup,playGoRoot);assert(fs::is_regular_file(playGo/"d0.pdb")&&fileHash(playGo/"d0.pdb")==playGoHash&&fs::is_regular_file(playGo/"d1.pdb")&&fs::file_size(playGo/"f0.pdb")==0&&fs::is_regular_file(playGo/"app.si")&&fs::is_directory(playGo/"config"/id)&&!fs::exists(playGoBackup/id));
  moveSource=0;moveRequestResult=-7;rejected=false;try{nativeMoveTitle("PPSA99991",id,0,1,playGoBackup,playGoRoot);}catch(...){rejected=true;}assert(rejected&&fs::is_regular_file(playGo/"d0.pdb")&&!fs::exists(playGoBackup/id));moveRequestResult=0;
  rejected=false;try{nativeMoveTitle("PPSA99991",id,0,2);}catch(...){rejected=true;}assert(rejected&&moveRequests==2);
  moveState=2;rejected=false;try{nativeMoveTitle("PPSA99991",id,0,1);}catch(...){rejected=true;}assert(rejected&&moveRequests==2);
  moveState=0;moveSource=2;rejected=false;try{nativeMoveTitle("PPSA99991",id,0,1);}catch(...){rejected=true;}assert(rejected&&moveRequests==2);
  cancelNativeMove();assert(moveCancels==1);
  moveSource=0;nativeMoveTitle("PPSA99991",id,0,1,playGoBackup,playGoRoot);fs::remove_all(playGo);moveSource=1;moveStateDelayMs=250;auto recoveryStarted=std::chrono::steady_clock::now();startNativeMoveRecovery(playGoBackup,playGoRoot);assert(std::chrono::steady_clock::now()-recoveryStarted<std::chrono::milliseconds(100));for(int i=0;i<100&&(!fs::is_regular_file(playGo/"d0.pdb")||fs::exists(playGoBackup/id));i++)std::this_thread::sleep_for(std::chrono::milliseconds(10));assert(fs::is_regular_file(playGo/"d0.pdb")&&!fs::exists(playGoBackup/id));moveStateDelayMs=0;fs::remove_all(playGoTestRoot);
  auto movedRoot=fs::temp_directory_path()/randomHex(8),movedPackage=movedRoot/"user/app/PPSA99991/app.pkg";fs::create_directories(movedPackage.parent_path());atomicBytes(movedPackage,"moved package");auto movedVolumes=Json::array();movedVolumes.add(Json::object({{"storageId","ext0"},{"path",movedRoot.string()},{"nativeMoveStorageType",int64_t(1)}}));auto moved=Json::object({{"titleId","PPSA99991"},{"storageId","ext0"},{"relativePath","app/PPSA99991"},{"nativeRegistered",true}});assert(observedNativePackage(moved,movedVolumes)==movedPackage);auto movedReceipt=Json::object({{"size",static_cast<int64_t>(fs::file_size(movedPackage))},{"sha256",fileHash(movedPackage)}});std::unordered_map<std::string,std::pair<fs::file_time_type,std::string>> movedCache;auto receiptState=receiptFileState(movedPackage,movedReceipt,movedCache);assert(receiptState.present&&!receiptState.checksumVerified);movedCache[movedPackage.string()]={fs::last_write_time(movedPackage),movedReceipt["sha256"].string()};receiptState=receiptFileState(movedPackage,movedReceipt,movedCache);assert(receiptState.present&&receiptState.checksumVerified);movedReceipt.set("sha256",std::string(64,'0'));receiptState=receiptFileState(movedPackage,movedReceipt,movedCache);assert(!receiptState.present&&!receiptState.checksumVerified);movedVolumes[size_t(0)].set("nativeMoveStorageType",int64_t(-1));assert(observedNativePackage(moved,movedVolumes).empty());fs::remove_all(movedRoot);
  Client client(Json::object({{"serverUrl","https://configured.example"}}));const std::string job="00000000-0000-4000-8000-000000000000",grant(64,'a'),iconGrant(64,'c'),packageHash(64,'b');const auto packagePath="/api/v1/native-downloads/"+job+"/"+grant+"/game.pkg",iconPath="/api/v1/native-downloads/"+job+"/"+iconGrant+"/icon.png";assert(client.nativeDownloadUrl(packagePath)=="https://configured.example"+packagePath);assert(client.nativeUpdateUrl("/api/v1/native-updates/PPSA99051/47/packages/"+packageHash+".pkg")=="https://configured.example/api/v1/native-updates/PPSA99051/47/packages/"+packageHash+".pkg");assert(client.nativeUpdateUrl("/api/v1/native-updates/PPSA99783/20/packages/"+packageHash+".pkg")=="https://configured.example/api/v1/native-updates/PPSA99783/20/packages/"+packageHash+".pkg");assert(client.nativeUpdateUrl("/api/v1/native-updates/PPSA99783/icon.png")=="https://configured.example/api/v1/native-updates/PPSA99783/icon.png");assert(client.nativeUpdateUrl("/api/v1/native-updates/grants/"+grant+"/PPSA99051/icon.png")=="https://configured.example/api/v1/native-updates/grants/"+grant+"/PPSA99051/icon.png");
  auto beforeOpenStory=requests;startNativeDownload(client.nativeUpdateUrl("/api/v1/native-updates/PPSA99783/20/packages/"+packageHash+".pkg"),"UP9000-PPSA99783_00-OPENSTORYPS50000","OpenStory",client.nativeUpdateUrl("/api/v1/native-updates/PPSA99783/icon.png"));assert(requests==beforeOpenStory+1);
  rejected=false;try{client.nativeDownloadUrl("https://another.example/game.pkg");}catch(...){rejected=true;}assert(rejected);rejected=false;try{client.nativeDownloadUrl("/api/v1/native-downloads/"+job+"/not-a-token/game.pkg");}catch(...){rejected=true;}assert(rejected);rejected=false;try{client.nativeDownloadUrl("/api/v1/native-downloads/"+job+"/"+grant+"/wrong.pkg");}catch(...){rejected=true;}assert(rejected);rejected=false;try{client.nativeDownloadUrl("/api/v1/native-updates/PPSA99051/47/packages/"+packageHash+".pkg");}catch(...){rejected=true;}assert(rejected);rejected=false;try{client.nativeUpdateUrl("/api/v1/native-updates/PPSA99999/47/packages/"+packageHash+".pkg");}catch(...){rejected=true;}assert(rejected);
  int listener=socket(AF_INET,SOCK_STREAM,0);assert(listener>=0);sockaddr_in address{};address.sin_family=AF_INET;address.sin_addr.s_addr=htonl(INADDR_LOOPBACK);assert(bind(listener,reinterpret_cast<sockaddr*>(&address),sizeof(address))==0&&listen(listener,4)==0);socklen_t addressSize=sizeof(address);assert(getsockname(listener,reinterpret_cast<sockaddr*>(&address),&addressSize)==0);
  std::string payload(4*1024*1024+17,'x');auto root=fs::temp_directory_path()/randomHex(8),source=root/"source",part=root/"part";fs::create_directories(root);atomicBytes(source,payload);auto hash=fileHash(source);
  std::atomic<bool> stop{false};std::atomic<int> ranges{0},reports{0},relayFetches{0};std::thread server(serve,listener,std::cref(payload),std::ref(stop),std::ref(ranges),std::ref(reports),std::ref(relayFetches));
  const auto fallbackOrigin="http://127.0.0.1:"+std::to_string(ntohs(address.sin_port));Client ranged(Json::object({{"serverUrl","http://127.0.0.1:9"},{"fallbackServerUrl",fallbackOrigin},{"allowInsecureLan",true}}));
  ranged.download("/api/v1/file",part,payload.size(),hash,[&](int64_t,int64_t){ranged.request("POST","/api/v1/progress",Json::object());});
  assert(ranged.nativeDownloadUrl(packagePath)==fallbackOrigin+packagePath);
  Client primaryProxied(Json::object({{"serverUrl",fallbackOrigin},{"serverProxyUrl",fallbackOrigin},{"allowInsecureLan",true}}));
  rejected=false;try{primaryProxied.nativeDownloadUrl(packagePath);}catch(const std::exception& error){rejected=std::string(error.what())=="NATIVE_INSTALL_DIRECT_URL_UNAVAILABLE";}assert(rejected);
  Client fallbackProxied(Json::object({{"serverUrl",fallbackOrigin},{"fallbackServerUrl","http://10.0.0.2:3150"},{"fallbackProxyUrl",fallbackOrigin},{"allowInsecureLan",true}}));
  assert(!fallbackProxied.nativeDownloadRelayRequired());assert(fallbackProxied.nativeDownloadUrl(packagePath)==fallbackOrigin+packagePath);
  Client proxied(Json::object({{"serverUrl","http://127.0.0.1:9"},{"fallbackServerUrl","http://10.0.0.2:3150"},{"fallbackProxyUrl",fallbackOrigin},{"allowInsecureLan",true}}));proxied.credential="relay-credential";proxied.request("GET","/api/v1/ping");
  rejected=false;try{proxied.nativeDownloadUrl(packagePath);}catch(const std::exception& error){rejected=std::string(error.what())=="NATIVE_INSTALL_DIRECT_URL_UNAVAILABLE";}assert(rejected);
  rejected=false;try{proxied.nativeUpdateUrl("/api/v1/native-updates/PPSA99051/47/packages/"+packageHash+".pkg");}catch(const std::exception& error){rejected=std::string(error.what())=="NATIVE_INSTALL_DIRECT_URL_UNAVAILABLE";}assert(rejected);
  std::string relayPackage;uint16_t relayPort=0;
  {
    NativeDownloadRelay relay(proxied,0);auto urls=relay.pin(packagePath,iconPath);relayPackage=urls.first;auto colon=relayPackage.find(':',7),slash=relayPackage.find('/',colon);relayPort=static_cast<uint16_t>(std::stoi(relayPackage.substr(colon+1,slash-colon-1)));
    auto head=relayRequest(relayPackage+"?product=0287&serverIpAddr=127.0.0.1&r=00000000","HEAD");assert(head.rfind("HTTP/1.1 200 OK",0)==0&&head.find("Content-Length: "+std::to_string(payload.size()))!=std::string::npos&&head.substr(head.find("\r\n\r\n")+4).empty());
    auto partial=relayRequest(relayPackage+"?product=0287&serverIpAddr=127.0.0.1&r=00000000","GET","Range: bytes=7-15\r\nIf-Range: \""+std::string(64,'a')+"\"\r\n");assert(partial.rfind("HTTP/1.1 206 Partial Content",0)==0&&partial.find("Content-Range: bytes 7-15/"+std::to_string(payload.size()))!=std::string::npos&&partial.substr(partial.find("\r\n\r\n")+4)==std::string(9,'x'));
    auto fetched=relayFetches.load();assert(relayRequest(relayPackage+".crc?product=0287&serverIpAddr=127.0.0.1&r=00000000").rfind("HTTP/1.1 404 Not Found",0)==0&&relayFetches==fetched);assert(relayRequest(relayPackage,"GET","Range: bytes=0-1,3-4\r\n").rfind("HTTP/1.1 400 Bad Request",0)==0&&relayFetches==fetched);
  }
  {NativeDownloadRelay restarted(proxied,relayPort);auto urls=restarted.pin(packagePath,iconPath);assert(urls.first==relayPackage&&relayRequest(urls.second,"HEAD").rfind("HTTP/1.1 200 OK",0)==0);}
  stop=true;shutdown(listener,SHUT_RDWR);close(listener);server.join();assert(fileHash(part)==hash&&ranges==2&&reports==2);fs::remove_all(root);
}
