#pragma once
#include "../common/client.hpp"
#include "../common/version.hpp"
#include <algorithm>
#include <cerrno>
#include <charconv>
#include <chrono>
#include <cctype>
#include <cstddef>
#include <cstring>
#include <functional>
#include <string_view>
#include <unordered_map>
#include <vector>
#include <arpa/inet.h>
#include <fcntl.h>
#include <netinet/in.h>
#include <sys/socket.h>
#include <sys/file.h>
#include <sys/stat.h>
#include <sys/time.h>
#include <sys/un.h>
#include <unistd.h>

namespace ps5library {
enum class LocalAgentAction { Invalid, Snapshot, HardwareProof, Refresh, Online, Connect, Offline, Disconnect, Close, AppUpdate, Media, Delete, Move, Launch, FormatPrepare, FormatConfirm, Cheats, CheatEnable, CheatDisable, MemoryScanTarget, MemoryScanStart, MemoryScanRefine, MemoryScanWatch, MemoryScanWrite, MemoryScanRestore, MemoryScanClear };
struct LocalAgentRequest {LocalAgentAction action=LocalAgentAction::Invalid;std::string titleId,kind,sourceStorageId,storageId,serverUrl,fallbackServerUrl,challenge,version,profileId,entryId,scanId,resultId,valueType,scanMode,scalarValue;bool allowInsecureLan=false,explicitApproval=false,freeze=false;int64_t rangeStart=-1,rangeEnd=-1;};

template<class Send> inline void notifyLocalAgentConnection(bool& notified,Send send){if(!notified)notified=send();}

inline bool localUnhex(std::string_view value,std::string& result){if(value.empty()||value.size()>4096||value.size()%2)return false;result.clear();result.reserve(value.size()/2);auto digit=[](char c)->int{if(c>='0'&&c<='9')return c-'0';if(c>='a'&&c<='f')return c-'a'+10;return -1;};for(size_t i=0;i<value.size();i+=2){auto high=digit(value[i]),low=digit(value[i+1]);if(high<0||low<0)return false;auto c=static_cast<char>((high<<4)|low);if(static_cast<unsigned char>(c)<0x20||c==0x7f)return false;result+=c;}return true;}
inline std::string_view localHeader(std::string_view request,std::string_view name){const auto headersEnd=request.find("\r\n\r\n");if(headersEnd==std::string_view::npos)return {};const auto prefix="\r\n"+std::string(name)+": ";auto at=request.find(prefix);if(at==std::string_view::npos||at>=headersEnd)return {};at+=prefix.size();auto end=request.find("\r\n",at);if(end==std::string_view::npos||end>headersEnd||request.find(prefix,end)!=std::string_view::npos)return {};return request.substr(at,end-at);}
inline bool localSecureEqual(std::string_view left,std::string_view right){const auto count=std::max(left.size(),right.size());std::size_t difference=left.size()^right.size();for(std::size_t i=0;i<count;i++){const unsigned char a=i<left.size()?static_cast<unsigned char>(left[i]):0,b=i<right.size()?static_cast<unsigned char>(right[i]):0;difference|=a^b;}return difference==0;}

inline bool localTitleId(std::string_view value){return value.size()==9&&(value.substr(0,4)=="PPSA"||value.substr(0,4)=="CUSA")&&std::all_of(value.begin()+4,value.end(),[](char c){return c>='0'&&c<='9';});}
inline bool localContentVersion(std::string_view value){if(value.size()!=10)return false;for(size_t i=0;i<value.size();i++)if(i==2||i==6?value[i]!='.':value[i]<'0'||value[i]>'9')return false;return true;}
inline bool localGameVersion(std::string_view value){int parts=0;while(!value.empty()){auto dot=value.find('.');auto part=value.substr(0,dot);if(part.empty()||part.size()>3||!std::all_of(part.begin(),part.end(),[](char c){return c>='0'&&c<='9';}))return false;parts++;if(dot==std::string_view::npos)break;value.remove_prefix(dot+1);}return parts==2||parts==3;}
inline bool localLowerHex(std::string_view value,size_t size){return value.size()==size&&std::all_of(value.begin(),value.end(),[](char c){return (c>='0'&&c<='9')||(c>='a'&&c<='f');});}
inline bool localMemoryType(std::string_view value){return value=="U8"||value=="U16"||value=="U32"||value=="U64"||value=="F32"||value=="F64";}
inline bool localScalarValue(std::string_view value){if(value.empty()||value.size()>32)return false;size_t i=value.front()=='-'?1:0;if(i==value.size())return false;bool digits=false,dot=false,exponent=false,exponentDigits=false;for(;i<value.size();i++){char c=value[i];if(c>='0'&&c<='9'){digits=true;if(exponent)exponentDigits=true;continue;}if(c=='.'&&!dot&&!exponent&&digits){dot=true;digits=false;continue;}if((c=='e'||c=='E')&&!exponent&&digits){exponent=true;exponentDigits=false;if(i+1<value.size()&&(value[i+1]=='+'||value[i+1]=='-'))i++;continue;}return false;}return digits&&(!exponent||exponentDigits);}
inline bool localMemorySensitive(LocalAgentAction action){return action==LocalAgentAction::CheatEnable||action==LocalAgentAction::CheatDisable||action==LocalAgentAction::MemoryScanTarget||action==LocalAgentAction::MemoryScanStart||action==LocalAgentAction::MemoryScanRefine||action==LocalAgentAction::MemoryScanWatch||action==LocalAgentAction::MemoryScanWrite||action==LocalAgentAction::MemoryScanRestore||action==LocalAgentAction::MemoryScanClear;}
inline bool localAppSensitive(LocalAgentAction action){return action==LocalAgentAction::HardwareProof||localMemorySensitive(action);}
inline std::vector<std::string_view> localPathParts(std::string_view value,size_t maximum=8){std::vector<std::string_view> parts;while(!value.empty()&&parts.size()<=maximum){auto slash=value.find('/');auto part=value.substr(0,slash);if(part.empty())return {};parts.push_back(part);if(slash==std::string_view::npos)return parts;value.remove_prefix(slash+1);}return {};}
inline bool localFrontendActive(const fs::path& shared){
  int fd=open((shared/"frontend.lock").c_str(),O_RDONLY|O_NOFOLLOW|O_NONBLOCK);if(fd<0)return false;struct File {int fd;~File(){close(fd);}} file{fd};struct stat status{};if(fstat(fd,&status)!=0||!S_ISREG(status.st_mode))return false;
  if(flock(fd,LOCK_EX|LOCK_NB)==0){flock(fd,LOCK_UN);return false;}return errno==EWOULDBLOCK||errno==EAGAIN;
}
inline fs::path localAgentSharedPath(const fs::path& sandboxRoot="/mnt/sandbox"){
  fs::path selected;std::string selectedName;std::error_code error;
  for(fs::directory_iterator it(sandboxRoot,fs::directory_options::skip_permission_denied,error),end;it!=end;it.increment(error)){if(error){error.clear();continue;}auto name=it->path().filename().string();if(name.size()!=13||name.rfind("PPSA99051_",0)!=0||!std::all_of(name.begin()+10,name.end(),[](char c){return c>='0'&&c<='9';}))continue;auto download=it->path()/"download0",shared=download/"ps5library";auto rootStatus=it->symlink_status(error),downloadStatus=fs::symlink_status(download,error),sharedStatus=fs::symlink_status(shared,error);if(error||fs::is_symlink(rootStatus)||!fs::is_directory(rootStatus)||fs::is_symlink(downloadStatus)||!fs::is_directory(downloadStatus)||fs::is_symlink(sharedStatus)||!fs::is_directory(sharedStatus)||!localFrontendActive(shared)){error.clear();continue;}if(selected.empty()||name>selectedName){selected=shared;selectedName=name;}error.clear();}
  return selected;
}
inline fs::path localAgentBackingSocketPath(const fs::path& sandboxRoot="/mnt/sandbox"){auto shared=localAgentSharedPath(sandboxRoot);return shared.empty()?fs::path():shared/"agent.sock";}
inline LocalAgentRequest parseNativeUpdateBridgeRequest(std::string_view request){
  LocalAgentRequest result;const auto headersEnd=request.find("\r\n\r\n"),lineEnd=request.find("\r\n");if(headersEnd==std::string_view::npos||lineEnd==std::string_view::npos)return result;
  const auto line=request.substr(0,lineEnd),prefix=std::string_view("GET /api/v1/agent/home-update/");if(line.rfind(prefix,0)!=0||line.size()!=prefix.size()+9+1+10+9||line.substr(line.size()-9)!=" HTTP/1.1")return result;
  const auto title=line.substr(prefix.size(),9),version=line.substr(prefix.size()+10,10);if(line[prefix.size()+9]!='/'||!nativeUpdateIdentity(title)||!localContentVersion(version))return result;
  result.action=LocalAgentAction::AppUpdate;result.titleId=title;result.version=version;return result;
}
inline std::string nativeNoUpdateXml(std::string_view titleId){const auto* identity=nativeUpdateIdentity(titleId);if(!identity)return {};return "<?xml version=\"1.0\" encoding=\"UTF-8\"?><title_patch ac_set_rev=\"0\" nptitleid=\""+std::string(identity->titleId)+"_00\" schema_ver=\"1.0\"><app_tag content_id=\""+identity->contentId+"\" name=\""+identity->name+"\" revision=\"0\"></app_tag></title_patch>";}
inline LocalAgentRequest parseLocalAgentRequest(std::string_view request,std::string_view sensitiveToken={},std::string_view bearer=localAgentCredential,bool sensitiveBearerOnly=false) {
  LocalAgentRequest result;const auto headersEnd=request.find("\r\n\r\n"),lineEnd=request.find("\r\n");
  if(headersEnd==std::string_view::npos||lineEnd==std::string_view::npos||bearer.empty()||!localSecureEqual(localHeader(request,"Authorization"),"Bearer "+std::string(bearer)))return result;
  const auto line=request.substr(0,lineEnd);const auto space=line.find(' '),last=line.rfind(' ');if(space==std::string_view::npos||last==space||line.substr(last)!=" HTTP/1.1")return result;
  const auto method=line.substr(0,space);auto path=line.substr(space+1,last-space-1);if(path=="/api/v1/agent/snapshot"&&method=="GET")result.action=LocalAgentAction::Snapshot;else if(path=="/api/v1/agent/hardware-proof"&&method=="GET")result.action=LocalAgentAction::HardwareProof;else if(path=="/api/v1/agent/refresh"&&method=="POST")result.action=LocalAgentAction::Refresh;else if(path=="/api/v1/agent/cheats"&&method=="GET")result.action=LocalAgentAction::Cheats;else if(path=="/api/v1/agent/online"&&method=="POST")result.action=LocalAgentAction::Online;else if(path=="/api/v1/agent/disconnect"&&method=="POST")result.action=LocalAgentAction::Disconnect;else if(path=="/api/v1/agent/close"&&method=="POST")result.action=LocalAgentAction::Close;
  else if(method=="POST"&&path.rfind("/api/v1/agent/app-update/",0)==0){auto value=path.substr(25);const auto slash=value.find('/');auto title=value.substr(0,slash);if(slash!=std::string_view::npos)value=value.substr(slash+1);if(slash==9&&nativeUpdateIdentity(title)&&localContentVersion(value)){result.action=LocalAgentAction::AppUpdate;result.titleId=title;result.version=value;}}
  else if(method=="POST"&&(path.rfind("/api/v1/agent/connect/",0)==0||path.rfind("/api/v1/agent/offline/",0)==0)){const bool offline=path.rfind("/api/v1/agent/offline/",0)==0;auto rest=path.substr(22);if(rest.size()>2&&rest[1]=='/'&&(rest[0]=='0'||rest[0]=='1')){auto encoded=rest.substr(2);auto split=encoded.find('/');auto primary=encoded.substr(0,split),fallback=split==std::string_view::npos?std::string_view():encoded.substr(split+1);if(localUnhex(primary,result.serverUrl)&&(fallback.empty()||fallback=="-"||localUnhex(fallback,result.fallbackServerUrl))){result.action=offline?LocalAgentAction::Offline:LocalAgentAction::Connect;result.allowInsecureLan=rest[0]=='1';}}}
  else {
    const std::string_view media="/api/v1/agent/media/",titles="/api/v1/agent/titles/",storage="/api/v1/agent/storage/",cheats="/api/v1/agent/cheats/",memory="/api/v1/agent/memory-scans/";
    if(method=="GET"&&path.rfind(media,0)==0){auto query=path.find('?');path=path.substr(0,query);auto rest=path.substr(media.size());auto slash=rest.find('/');if(slash!=std::string_view::npos&&localTitleId(rest.substr(0,slash))&&(rest.substr(slash+1)=="cover"||rest.substr(slash+1)=="hero"||rest.substr(slash+1)=="music")){result.action=LocalAgentAction::Media;result.titleId=rest.substr(0,slash);result.kind=rest.substr(slash+1);}}
    else if(method=="POST"&&path.rfind(titles,0)==0){auto rest=path.substr(titles.size());auto slash=rest.find('/');if(slash!=std::string_view::npos&&localTitleId(rest.substr(0,slash))){result.titleId=rest.substr(0,slash);rest=rest.substr(slash+1);auto valid=[](std::string_view value){return !value.empty()&&value.size()<=64&&std::all_of(value.begin(),value.end(),[](char c){return std::isalnum(static_cast<unsigned char>(c))||c=='_'||c=='-';});};if(rest=="launch")result.action=LocalAgentAction::Launch;else if(rest.rfind("delete/",0)==0&&valid(rest.substr(7))){result.action=LocalAgentAction::Delete;result.storageId=rest.substr(7);}else if(rest.rfind("move/",0)==0){auto stores=rest.substr(5);auto split=stores.find('/');if(split!=std::string_view::npos&&valid(stores.substr(0,split))&&valid(stores.substr(split+1))){result.action=LocalAgentAction::Move;result.sourceStorageId=stores.substr(0,split);result.storageId=stores.substr(split+1);}}}}
    else if(method=="POST"&&path.rfind(storage,0)==0){auto rest=path.substr(storage.size());auto slash=rest.find('/');if(slash!=std::string_view::npos){auto id=rest.substr(0,slash);auto action=rest.substr(slash+1);const bool usb=id.size()>3&&id.rfind("usb",0)==0&&std::all_of(id.begin()+3,id.end(),[](char c){return c>='0'&&c<='9';});if(usb&&action=="format/prepare"){result.action=LocalAgentAction::FormatPrepare;result.storageId=id;}else if(usb&&action.rfind("format/confirm/",0)==0){auto token=action.substr(15);if(token.size()==64&&std::all_of(token.begin(),token.end(),[](char c){return (c>='0'&&c<='9')||(c>='a'&&c<='f');})){result.action=LocalAgentAction::FormatConfirm;result.storageId=id;result.challenge=token;}}}}
    else if(path.rfind(memory,0)==0){
      auto parts=localPathParts(path.substr(memory.size()));
      if(method=="GET"&&parts.size()==1&&parts[0]=="target")result.action=LocalAgentAction::MemoryScanTarget;
      else if(method=="POST"&&parts.size()==1&&parts[0]=="clear")result.action=LocalAgentAction::MemoryScanClear;
      else if(method=="POST"&&(parts.size()==5||parts.size()==6)&&parts[0]=="start"&&localTitleId(parts[1])&&localGameVersion(parts[2])&&localMemoryType(parts[3])&&((parts[4]=="UNKNOWN"&&parts.size()==5)||(parts[4]=="EXACT"&&parts.size()==6&&localScalarValue(parts[5])))){result.action=LocalAgentAction::MemoryScanStart;result.titleId=parts[1];result.version=parts[2];result.valueType=parts[3];result.scanMode=parts[4];if(parts.size()==6)result.scalarValue=parts[5];}
      else if(parts.size()>=1&&localLowerHex(parts[0],32)){
        result.scanId=parts[0];
        if(method=="GET"&&parts.size()==1)result.action=LocalAgentAction::MemoryScanWatch;
        else if(method=="POST"&&(parts.size()==3||parts.size()==4)&&parts[1]=="refine"&&((parts[2]=="EXACT"&&parts.size()==4&&localScalarValue(parts[3]))||((parts[2]=="CHANGED"||parts[2]=="UNCHANGED"||parts[2]=="INCREASED"||parts[2]=="DECREASED")&&parts.size()==3))){result.action=LocalAgentAction::MemoryScanRefine;result.scanMode=parts[2];if(parts.size()==4)result.scalarValue=parts[3];}
        else if(method=="POST"&&(parts.size()==4||parts.size()==5)&&parts[1]=="results"&&localLowerHex(parts[2],32)){result.resultId=parts[2];if(parts[3]=="restore"&&parts.size()==4){result.action=LocalAgentAction::MemoryScanRestore;result.explicitApproval=localSecureEqual(localHeader(request,"X-PS5Library-Memory-Approval"),result.scanId);}else if((parts[3]=="write"||parts[3]=="freeze")&&parts.size()==5&&localScalarValue(parts[4])){result.action=LocalAgentAction::MemoryScanWrite;result.scalarValue=parts[4];result.freeze=parts[3]=="freeze";result.explicitApproval=localSecureEqual(localHeader(request,"X-PS5Library-Memory-Approval"),result.scanId);}}
      }
    }
    else if(method=="POST"&&path.rfind(cheats,0)==0){auto rest=path.substr(cheats.size());auto first=rest.find('/'),second=first==std::string_view::npos?first:rest.find('/',first+1);auto hex=[](std::string_view value){return value.size()==64&&std::all_of(value.begin(),value.end(),[](char c){return (c>='0'&&c<='9')||(c>='a'&&c<='f');});};if(first!=std::string_view::npos&&second!=std::string_view::npos&&hex(rest.substr(0,first))&&hex(rest.substr(first+1,second-first-1))){auto action=rest.substr(second+1);if(action=="enable")result.action=LocalAgentAction::CheatEnable;else if(action=="disable")result.action=LocalAgentAction::CheatDisable;if(result.action!=LocalAgentAction::Invalid){result.profileId=rest.substr(0,first);result.entryId=rest.substr(first+1,second-first-1);if(!sensitiveBearerOnly&&(sensitiveToken.empty()||!localSecureEqual(localHeader(request,"X-PS5Library-Cheat-Session"),sensitiveToken)))result=LocalAgentRequest{};else if(result.action==LocalAgentAction::CheatEnable)result.explicitApproval=localSecureEqual(localHeader(request,"X-PS5Library-Cheat-Approval"),result.profileId);}}}
  }
  if(result.action==LocalAgentAction::Media)if(auto at=request.find("\r\nRange: bytes=");at!=std::string_view::npos){at+=15;auto dash=request.find('-',at),end=request.find("\r\n",at);if(dash==std::string_view::npos||end==std::string_view::npos||dash>=end){result.action=LocalAgentAction::Invalid;return result;}auto first=request.substr(at,dash-at),lastPart=request.substr(dash+1,end-dash-1);auto parsed=std::from_chars(first.data(),first.data()+first.size(),result.rangeStart);if(parsed.ec!=std::errc()||parsed.ptr!=first.data()+first.size()||result.rangeStart<0){result.action=LocalAgentAction::Invalid;return result;}if(!lastPart.empty()){parsed=std::from_chars(lastPart.data(),lastPart.data()+lastPart.size(),result.rangeEnd);if(parsed.ec!=std::errc()||parsed.ptr!=lastPart.data()+lastPart.size()||result.rangeEnd<result.rangeStart){result.action=LocalAgentAction::Invalid;return result;}}}
  if(localAppSensitive(result.action)){if(!sensitiveBearerOnly&&(sensitiveToken.empty()||!localSecureEqual(localHeader(request,"X-PS5Library-Cheat-Session"),sensitiveToken)))return LocalAgentRequest{};}
  if(sensitiveBearerOnly&&!localMemorySensitive(result.action))return LocalAgentRequest{};
  return result;
}
inline Json localAgentFailure(const LocalAgentRequest& request,const std::string& error){auto result=Json::object({{"error",error}});if(request.action==LocalAgentAction::CheatEnable||request.action==LocalAgentAction::CheatDisable){result.set("profileId",request.profileId);result.set("entryId",request.entryId);result.set("state","ERROR");result.set("requestedEnabled",request.action==LocalAgentAction::CheatEnable);result.set("approvalRequired",error=="LOCAL_APPROVAL_REQUIRED");result.set("changedAtUnixMs",static_cast<int64_t>(std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::system_clock::now().time_since_epoch()).count()));}return result;}
inline bool localLaunchable(const Json& snapshot,const std::string& title){auto items=snapshot["inventory"];for(size_t i=0;i<items.size();i++)if(items[i]["titleId"].string()==title&&items[i]["available"].boolean()&&(items[i]["registered"].boolean()||items[i]["source"].string()=="INSTALLED_TITLE"))return true;return false;}

inline fs::path localMediaPath(const Json& snapshot,const Json& item,const std::string& kind){
  const auto title=item["titleId"].string();if(!localTitleId(title)||!item["available"].boolean())return {};
  std::vector<std::string> names=kind=="cover"?std::vector<std::string>{"icon0.png","icon0.jpg","icon0.jpeg"}:kind=="hero"?std::vector<std::string>{"pic1.png","pic0.png","pic2.png","pic1.jpg","pic0.jpg","icon0.png"}:kind=="music"?std::vector<std::string>{"snd0.at9"}:std::vector<std::string>{};
  const uintmax_t limit=kind=="music"?8*1024*1024:32*1024*1024;auto find=[&](const fs::path& root,const std::string& prefix){for(const auto& name:names)try{auto file=beneath(root,prefix+name);auto status=fs::symlink_status(file);if(!fs::is_symlink(status)&&fs::is_regular_file(status)){auto size=fs::file_size(file);if(size&&size<=limit)return file;}}catch(...){ }return fs::path();};
  for(const auto& root:std::vector<std::pair<fs::path,std::string>>{{"/user/appmeta",title+"/"},{"/user/app",title+"/"},{"/user/app",title+"/sce_sys/"}})if(auto file=find(root.first,root.second);!file.empty())return file;
  auto storage=snapshot["storage"];for(size_t i=0;i<storage.size();i++)if(storage[i]["storageId"].string()==item["storageId"].string())if(auto file=find(storage[i]["path"].string(),item["relativePath"].string()+"/sce_sys/");!file.empty())return file;return {};
}
inline fs::path localMediaPath(const Json& snapshot,const std::string& title,const std::string& kind){auto items=snapshot["inventory"];for(size_t i=0;i<items.size();i++)if(items[i]["titleId"].string()==title)if(auto file=localMediaPath(snapshot,items[i],kind);!file.empty())return file;return {};}
inline void addLocalMedia(Json snapshot,std::unordered_map<std::string,std::pair<fs::file_time_type,std::string>>& hashes,const std::function<bool()>& cancelled={}){
  auto items=snapshot["inventory"];for(size_t i=0;i<items.size();i++){auto item=items[i],media=Json::object();for(const auto* kind:{"cover","hero","music"})try{auto file=localMediaPath(snapshot,item,kind);if(file.empty())continue;auto size=fs::file_size(file);auto stamp=fs::last_write_time(file);auto version=std::to_string(static_cast<long long>(stamp.time_since_epoch().count()))+"-"+std::to_string(static_cast<unsigned long long>(size));auto value=Json::object({{"url","/api/v1/agent/media/"+item["titleId"].string()+"/"+kind+"?v="+version},{"size",static_cast<int64_t>(size)}});if(std::string(kind)=="music"){auto found=hashes.find(file.string());if(found==hashes.end()||found->second.first!=stamp)hashes[file.string()]={stamp,fileHash(file,cancelled)};value.set("sha256",hashes[file.string()].second);}media.set(kind,value);}catch(...){ }item.set("localMedia",media);}
}
inline std::string localAgentPayload(const Json& body,size_t limit){
  auto payload=body.dump();if(payload.size()<=limit)return payload;auto source=body["snapshot"];if(!source.isObject())return {};
  auto summarizeSaves=[](const Json& saves){auto summary=Json::object({{"items",Json::array()},{"totalItems",static_cast<int64_t>(saves["items"].size())},{"complete",false},{"truncated",true}});for(const auto* key:{"source","localUserId"})if(!saves[key].null())summary.set(key,saves[key]);return summary;};
  auto trimmed=Json::parse(payload),trimmedSnapshot=trimmed["snapshot"];trimmedSnapshot.set("saveData",summarizeSaves(trimmedSnapshot["saveData"]));trimmedSnapshot.set("cheats",Json::array());trimmedSnapshot.set("localPayloadTruncated",true);auto firstOmitted=Json::array();firstOmitted.add("saveData.items");firstOmitted.add("cheats");trimmedSnapshot.set("localPayloadOmitted",firstOmitted);payload=trimmed.dump();if(payload.size()<=limit)return payload;
  auto inventory=Json::array();for(size_t i=0;i<source["inventory"].size();i++){auto item=source["inventory"][i],compact=Json::object();for(const auto* key:{"size","available","registered","nativeRegistered","registrationBlocked","canDelete","canMove","backportFiles"})if(!item[key].null())compact.set(key,item[key]);for(const auto& field:std::vector<std::pair<const char*,size_t>>{{"title",200},{"titleId",16},{"contentId",80},{"version",30},{"platform",16},{"storageId",128},{"relativePath",1024},{"source",32},{"method",32},{"releaseId",128},{"sha256",64},{"backportProfileId",128}}){auto value=item[field.first].string();if(!value.empty()&&value.size()<=field.second)compact.set(field.first,value);}inventory.add(compact);}
  auto snapshot=Json::object({{"inventory",inventory},{"saveData",summarizeSaves(source["saveData"])},{"cheats",Json::array()},{"activeTransfers",Json::array()},{"localPayloadTruncated",true}});for(const auto* key:{"firmware","runtime","runtimeStatus","clientVersion","agentVersion","trophySummary","capabilities","storage","storageFormat","libraryRevision","inventoryComplete","shadowMountVersion","shadowMountFakelib","standaloneBackPork"})if(!source[key].null())snapshot.set(key,source[key]);auto omitted=Json::array();omitted.add("saveData.items");omitted.add("cheats");omitted.add("inventory.localMedia");snapshot.set("localPayloadOmitted",omitted);
  auto compact=Json::object({{"snapshot",snapshot}});if(!body["device"].null())compact.set("device",body["device"]);payload=compact.dump();return payload.size()<=limit?payload:std::string();
}

class LocalAgentServer {
  int listener_=-1;uint16_t port_=0;in_addr_t boundAddress_=0;bool fixedAddress_=false;fs::path socketPath_;dev_t socketDevice_=0;ino_t socketInode_=0;
  std::string sensitiveToken_,bearer_=localAgentCredential;bool sensitiveBearerOnly_=false;
  void ready(){if(listen(listener_,4)!=0){close(listener_);listener_=-1;throw std::runtime_error("Local agent listen failed");}auto flags=fcntl(listener_,F_GETFL,0);if(flags<0||fcntl(listener_,F_SETFL,flags|O_NONBLOCK)!=0){close(listener_);listener_=-1;throw std::runtime_error("Local agent socket setup failed");}}
  static bool sendAll(int peer,const char* value,size_t size){size_t offset=0;while(offset<size){
#ifdef MSG_NOSIGNAL
      const auto count=send(peer,value+offset,size-offset,MSG_NOSIGNAL);
#else
      const auto count=send(peer,value+offset,size-offset,0);
#endif
      if(count<0&&errno==EINTR)continue;if(count<=0)return false;offset+=static_cast<size_t>(count);}return true;}
  static bool sendAll(int peer,const std::string& value){return sendAll(peer,value.data(),value.size());}
  static void sendFile(int peer,const fs::path& path,const LocalAgentRequest& request){
    int fd=open(path.c_str(),O_RDONLY|O_NOFOLLOW);if(fd<0)throw std::runtime_error("Local media unavailable");struct File {int fd;~File(){close(fd);}} guard{fd};struct stat stat{};auto extension=path.extension().string();const auto limit=extension==".at9"?8*1024*1024:32*1024*1024;if(fstat(fd,&stat)!=0||!S_ISREG(stat.st_mode)||stat.st_size<=0||stat.st_size>limit)throw std::runtime_error("Local media unavailable");
    int64_t first=request.rangeStart<0?0:request.rangeStart,last=request.rangeEnd<0?stat.st_size-1:request.rangeEnd;if(first>=stat.st_size||last>=stat.st_size||last<first)throw std::runtime_error("Invalid media range");const auto count=last-first+1;const char* type=extension==".at9"?"audio/atrac9":(extension==".jpg"||extension==".jpeg")?"image/jpeg":"image/png";const bool partial=request.rangeStart>=0;
    std::string header="HTTP/1.1 "+std::string(partial?"206 Partial Content":"200 OK")+"\r\nContent-Type: "+type+"\r\nCache-Control: private, max-age=31536000, immutable\r\nAccept-Ranges: bytes\r\nConnection: close\r\nContent-Length: "+std::to_string(count)+"\r\n";if(partial)header+="Content-Range: bytes "+std::to_string(first)+"-"+std::to_string(last)+"/"+std::to_string(stat.st_size)+"\r\n";header+="\r\n";if(!sendAll(peer,header)||lseek(fd,first,SEEK_SET)<0)return;
    char buffer[64*1024];int64_t remaining=count;while(remaining>0){auto readBytes=read(fd,buffer,static_cast<size_t>(std::min<int64_t>(sizeof(buffer),remaining)));if(readBytes<=0)return;if(!sendAll(peer,buffer,static_cast<size_t>(readBytes)))return;remaining-=readBytes;}
  }
public:
  explicit LocalAgentServer(uint16_t port=localAgentPort,const char* fixedHost=nullptr,std::string sensitiveToken={},std::string bearer=localAgentCredential,bool sensitiveBearerOnly=false):sensitiveToken_(std::move(sensitiveToken)),bearer_(std::move(bearer)),sensitiveBearerOnly_(sensitiveBearerOnly){
    listener_=socket(AF_INET,SOCK_STREAM,0);if(listener_<0)throw std::runtime_error("Local agent socket unavailable");int reuse=1;setsockopt(listener_,SOL_SOCKET,SO_REUSEADDR,&reuse,sizeof(reuse));sockaddr_in address{};address.sin_family=AF_INET;address.sin_port=htons(port);fixedAddress_=fixedHost!=nullptr;auto host=fixedAddress_?std::string(fixedHost):localAgentAddress();if(inet_pton(AF_INET,host.c_str(),&address.sin_addr)!=1){close(listener_);listener_=-1;throw std::runtime_error("Local agent address unavailable");}
#ifdef PS5
    address.sin_len=sizeof(address);
#endif
    boundAddress_=address.sin_addr.s_addr;
    if(bind(listener_,reinterpret_cast<sockaddr*>(&address),sizeof(address))!=0){close(listener_);listener_=-1;throw std::runtime_error("Local agent port unavailable");}ready();socklen_t size=sizeof(address);if(getsockname(listener_,reinterpret_cast<sockaddr*>(&address),&size)!=0){close(listener_);listener_=-1;throw std::runtime_error("Local agent socket setup failed");}port_=ntohs(address.sin_port);
  }
  explicit LocalAgentServer(const fs::path& path,std::string sensitiveToken={},std::string bearer=localAgentCredential,bool sensitiveBearerOnly=false):socketPath_(path),sensitiveToken_(std::move(sensitiveToken)),bearer_(std::move(bearer)),sensitiveBearerOnly_(sensitiveBearerOnly){auto value=path.string();sockaddr_un address{};if(value.empty()||value.size()>=sizeof(address.sun_path))throw std::runtime_error("Invalid local agent socket path");struct stat parent{},existing{};if(lstat(path.parent_path().c_str(),&parent)!=0||!S_ISDIR(parent.st_mode)||S_ISLNK(parent.st_mode))throw std::runtime_error("Local agent socket directory unavailable");if(lstat(value.c_str(),&existing)==0){if(!S_ISSOCK(existing.st_mode)||unlink(value.c_str())!=0)throw std::runtime_error("Unsafe local agent socket path");}else if(errno!=ENOENT)throw std::runtime_error("Local agent socket path unavailable");listener_=socket(AF_UNIX,SOCK_STREAM,0);if(listener_<0)throw std::runtime_error("Local agent socket unavailable");address.sun_family=AF_UNIX;std::memcpy(address.sun_path,value.c_str(),value.size()+1);auto size=static_cast<socklen_t>(offsetof(sockaddr_un,sun_path)+value.size()+1);
#ifdef PS5
    address.sun_len=static_cast<unsigned char>(size);
#endif
    if(bind(listener_,reinterpret_cast<sockaddr*>(&address),size)!=0||chmod(value.c_str(),0666)!=0||lstat(value.c_str(),&existing)!=0){close(listener_);listener_=-1;unlink(value.c_str());throw std::runtime_error("Local agent socket unavailable");}socketDevice_=existing.st_dev;socketInode_=existing.st_ino;try{ready();}catch(...){unlink(value.c_str());throw;}}
  bool available()const{if(socketPath_.empty()){if(fixedAddress_)return listener_>=0;try{in_addr address{};return listener_>=0&&inet_pton(AF_INET,localAgentAddress().c_str(),&address)==1&&address.s_addr==boundAddress_;}catch(...){return false;}}struct stat status{};return listener_>=0&&lstat(socketPath_.c_str(),&status)==0&&S_ISSOCK(status.st_mode)&&status.st_dev==socketDevice_&&status.st_ino==socketInode_;}
  ~LocalAgentServer(){if(listener_>=0)close(listener_);if(available())unlink(socketPath_.c_str());}LocalAgentServer(const LocalAgentServer&)=delete;LocalAgentServer& operator=(const LocalAgentServer&)=delete;uint16_t port()const{return port_;}
  bool poll(const std::function<Json(const LocalAgentRequest&)>& handle,const std::function<fs::path(const LocalAgentRequest&)>& file={},const std::function<void()>& connected={},const std::function<void(const LocalAgentRequest&)>& nativeUpdate={}){
    sockaddr_in peerAddress{};socklen_t peerSize=sizeof(peerAddress);int peer=socketPath_.empty()?accept(listener_,reinterpret_cast<sockaddr*>(&peerAddress),&peerSize):accept(listener_,nullptr,nullptr);if(peer<0){if(errno==EAGAIN||errno==EWOULDBLOCK)return false;throw std::runtime_error("Local agent accept failed");}struct Peer {int fd;~Peer(){close(fd);}} guard{peer};if(socketPath_.empty()&&(peerAddress.sin_family!=AF_INET||peerAddress.sin_addr.s_addr!=boundAddress_))return true;auto flags=fcntl(peer,F_GETFL,0);if(flags<0||fcntl(peer,F_SETFL,flags&~O_NONBLOCK)!=0)return true;timeval timeout{10,0};setsockopt(peer,SOL_SOCKET,SO_RCVTIMEO,&timeout,sizeof(timeout));setsockopt(peer,SOL_SOCKET,SO_SNDTIMEO,&timeout,sizeof(timeout));
    constexpr size_t requestLimit=8192;std::string request;char bytes[1024];while(request.size()<requestLimit&&request.find("\r\n\r\n")==std::string::npos){auto count=recv(peer,bytes,std::min(sizeof(bytes),requestLimit-request.size()),0);if(count<=0)break;request.append(bytes,static_cast<size_t>(count));}
    if(nativeUpdate){auto update=parseNativeUpdateBridgeRequest(request);if(update.action!=LocalAgentAction::AppUpdate){sendAll(peer,"HTTP/1.1 404 Not Found\r\nConnection: close\r\nContent-Length: 0\r\n\r\n");return true;}auto payload=nativeNoUpdateXml(update.titleId);auto response="HTTP/1.1 200 OK\r\nContent-Type: application/xml; charset=utf-8\r\nCache-Control: no-store\r\nConnection: close\r\nContent-Length: "+std::to_string(payload.size())+"\r\n\r\n"+payload;if(sendAll(peer,response))nativeUpdate(update);return true;}
    const auto parsed=parseLocalAgentRequest(request,sensitiveToken_,bearer_,sensitiveBearerOnly_);
    if(parsed.action==LocalAgentAction::Media&&file)try{sendFile(peer,file(parsed),parsed);return true;}catch(...){sendAll(peer,"HTTP/1.1 404 Not Found\r\nConnection: close\r\nContent-Length: 0\r\n\r\n");return true;}
    int status=parsed.action==LocalAgentAction::Invalid?404:200;Json body;try{body=status==200?handle(parsed):Json::object({{"error","Not found"}});}catch(const std::exception& e){status=409;body=localAgentFailure(parsed,e.what());}catch(...){status=503;body=localAgentFailure(parsed,"Local action unavailable");}auto payload=localAgentPayload(body,12*1024*1024);if(payload.empty()){status=503;payload=Json::object({{"error","Local scan too large"}}).dump();}const char* reason=status==200?"OK":status==404?"Not Found":status==409?"Conflict":"Service Unavailable";if(sendAll(peer,"HTTP/1.1 "+std::to_string(status)+" "+reason+"\r\nContent-Type: application/json\r\nCache-Control: no-store\r\nConnection: close\r\nContent-Length: "+std::to_string(payload.size())+"\r\n\r\n"+payload)&&status==200&&connected)connected();return true;
  }
};
}
