#include "memory_scanner.hpp"
#include "../common/client.hpp"
#include <algorithm>
#include <array>
#include <cerrno>
#include <charconv>
#include <chrono>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <limits>
#include <openssl/evp.h>
#include <regex>
#include <stdexcept>

namespace ps5library {
namespace {
constexpr std::size_t maxValueBytes=8,readChunkBytes=256*1024;
using Bytes=std::array<unsigned char,maxValueBytes>;
enum class Kind { U8,U16,U32,U64,F32,F64 };
struct Format {Kind kind;std::size_t size;const char* name;};
const std::regex titlePattern("(PPSA|CUSA)[0-9]{5}"),versionPattern("[0-9]{1,3}(\\.[0-9]{1,3}){1,2}");

Format format(std::string_view name){
  if(name=="U8")return {Kind::U8,1,"U8"};if(name=="U16")return {Kind::U16,2,"U16"};if(name=="U32")return {Kind::U32,4,"U32"};if(name=="U64")return {Kind::U64,8,"U64"};if(name=="F32")return {Kind::F32,4,"F32"};if(name=="F64")return {Kind::F64,8,"F64"};throw std::runtime_error("MEMORY_VALUE_TYPE_INVALID");
}
std::uint64_t unsignedValue(const Bytes& bytes,std::size_t size){std::uint64_t value=0;for(std::size_t i=0;i<size;i++)value|=static_cast<std::uint64_t>(bytes[i])<<(i*8);return value;}
Bytes parse(const Format& type,const std::string& text){
  if(text.empty()||text.size()>64)throw std::runtime_error("MEMORY_VALUE_INVALID");Bytes bytes{};
  if(type.kind==Kind::F32||type.kind==Kind::F64){char* end=nullptr;errno=0;if(type.kind==Kind::F32){const auto value=std::strtof(text.c_str(),&end);if(errno||end!=text.c_str()+text.size()||!std::isfinite(value))throw std::runtime_error("MEMORY_VALUE_INVALID");std::memcpy(bytes.data(),&value,sizeof(value));}else{const auto value=std::strtod(text.c_str(),&end);if(errno||end!=text.c_str()+text.size()||!std::isfinite(value))throw std::runtime_error("MEMORY_VALUE_INVALID");std::memcpy(bytes.data(),&value,sizeof(value));}return bytes;}
  std::uint64_t value=0;auto converted=std::from_chars(text.data(),text.data()+text.size(),value);const auto bits=type.size*8;if(converted.ec!=std::errc()||converted.ptr!=text.data()+text.size()||(bits<64&&value>((std::uint64_t{1}<<bits)-1)))throw std::runtime_error("MEMORY_VALUE_INVALID");for(std::size_t i=0;i<type.size;i++)bytes[i]=static_cast<unsigned char>(value>>(i*8));return bytes;
}
std::string display(const Format& type,const Bytes& bytes){
  char result[64]{};if(type.kind==Kind::F32){float value=0;std::memcpy(&value,bytes.data(),sizeof(value));if(!std::isfinite(value))return "nan";std::snprintf(result,sizeof(result),"%.9g",static_cast<double>(value));return result;}if(type.kind==Kind::F64){double value=0;std::memcpy(&value,bytes.data(),sizeof(value));if(!std::isfinite(value))return "nan";std::snprintf(result,sizeof(result),"%.17g",value);return result;}auto value=unsignedValue(bytes,type.size);auto converted=std::to_chars(result,result+sizeof(result),value);return converted.ec==std::errc()?std::string(result,converted.ptr):std::string{};
}
bool equal(const Bytes& left,const Bytes& right,std::size_t size){return std::equal(left.begin(),left.begin()+static_cast<std::ptrdiff_t>(size),right.begin());}
int compare(const Format& type,const Bytes& left,const Bytes& right){
  if(type.kind==Kind::F32){float a=0,b=0;std::memcpy(&a,left.data(),4);std::memcpy(&b,right.data(),4);if(std::isnan(a)||std::isnan(b))return 0;return a<b?-1:a>b?1:0;}if(type.kind==Kind::F64){double a=0,b=0;std::memcpy(&a,left.data(),8);std::memcpy(&b,right.data(),8);if(std::isnan(a)||std::isnan(b))return 0;return a<b?-1:a>b?1:0;}const auto a=unsignedValue(left,type.size),b=unsignedValue(right,type.size);return a<b?-1:a>b?1:0;
}
bool sameTarget(const CheatTarget& left,const CheatTarget& right){
  if(left.token!=right.token||left.pid!=right.pid||left.startedSeconds!=right.startedSeconds||left.startedMicroseconds!=right.startedMicroseconds||left.moduleBase!=right.moduleBase||left.moduleSize!=right.moduleSize||left.titleId!=right.titleId||left.version!=right.version||left.process!=right.process||left.contentId!=right.contentId||left.executableSha256!=right.executableSha256||left.ranges.size()!=right.ranges.size())return false;for(std::size_t i=0;i<left.ranges.size();i++){const auto& a=left.ranges[i];const auto& b=right.ranges[i];if(a.offset!=b.offset||a.size!=b.size||a.readable!=b.readable||a.writable!=b.writable)return false;}return true;
}
bool within(const CheatMemoryRange& range,std::uint64_t offset,std::size_t size){return size&&offset>=range.offset&&offset-range.offset<=range.size&&size<=range.size-(offset-range.offset);}
std::vector<unsigned char> readExact(CheatRuntime& runtime,const CheatTarget& target,std::uint64_t offset,std::size_t size){auto bytes=runtime.scanRead(target,offset,size);if(bytes.size()!=size)throw std::runtime_error("MEMORY_READ_INCOMPLETE");return bytes;}
std::string opaque(std::string_view secret,std::uint64_t serial){std::array<unsigned char,40> input{};std::copy_n(secret.data(),std::min(secret.size(),std::size_t(32)),input.data());for(unsigned i=0;i<8;i++)input[32+i]=static_cast<unsigned char>(serial>>(i*8));unsigned char hash[EVP_MAX_MD_SIZE]{};unsigned size=0;if(EVP_Digest(input.data(),input.size(),hash,&size,EVP_sha256(),nullptr)!=1||size<16)throw std::runtime_error("MEMORY_RESULT_ID_FAILED");static constexpr char hex[]="0123456789abcdef";std::string result(32,'0');for(unsigned i=0;i<16;i++){result[i*2]=hex[hash[i]>>4];result[i*2+1]=hex[hash[i]&15];}return result;}
}

struct MemoryScanner::Session {
  struct Candidate {std::string id;std::uint64_t offset=0;std::size_t range=0;Bytes previous{},original{},frozenValue{};bool writable=false,modified=false,frozen=false;};
  struct Segment {std::size_t range=0;std::uint64_t start=0;std::vector<unsigned char> previous,active;std::size_t slots=0;};
  std::string id,resultSecret;CheatTarget target;Format type{Kind::U32,4,"U32"};std::vector<Candidate> candidates;std::vector<Segment> baseline;std::uint64_t totalReadableBytes=0,scannedBytes=0,activeCount=0,nextSerial=0;std::chrono::steady_clock::time_point nextReconcile{};
};

namespace {
std::uint64_t validateRanges(const CheatTarget& target){
  if(!target.moduleBase||!target.moduleSize||target.moduleBase>std::numeric_limits<std::uint64_t>::max()-target.moduleSize||target.ranges.empty())throw std::runtime_error("MEMORY_RANGES_UNAVAILABLE");std::uint64_t last=0,total=0;bool first=true;for(const auto& range:target.ranges){if(!range.size||range.offset>target.moduleSize||range.size>target.moduleSize-range.offset||(!first&&range.offset<last))throw std::runtime_error("MEMORY_RANGES_INVALID");first=false;last=range.offset+range.size;if(range.readable&&range.writable){if(total>maxMemoryScanBytes||range.size>maxMemoryScanBytes-total)throw std::runtime_error("MEMORY_SCAN_RANGE_LIMIT");total+=range.size;}}if(!total)throw std::runtime_error("MEMORY_RANGES_UNAVAILABLE");return total;
}
MemoryScanner::Session& require(std::unique_ptr<MemoryScanner::Session>& session,const std::string& id){if(!session||session->id!=id)throw std::runtime_error("MEMORY_SCAN_NOT_FOUND");return *session;}
MemoryScanner::Session::Candidate& selected(MemoryScanner::Session& session,const std::string& id){auto found=std::find_if(session.candidates.begin(),session.candidates.end(),[&](const auto& item){return item.id==id;});if(found==session.candidates.end())throw std::runtime_error("MEMORY_RESULT_NOT_FOUND");return *found;}
std::vector<Bytes> readCandidates(CheatRuntime& runtime,MemoryScanner::Session& session,std::size_t limit){
  auto running=runtime.running(session.target.process);if(!running||!sameTarget(*running,session.target))throw std::runtime_error("CHEAT_TARGET_CHANGED");limit=std::min(limit,session.candidates.size());std::vector<Bytes> values(limit);std::size_t i=0;while(i<limit){const auto start=session.candidates[i].offset,range=session.candidates[i].range,rangeEnd=session.target.ranges[range].offset+session.target.ranges[range].size;std::size_t last=i;while(last+1<limit&&session.candidates[last+1].range==range&&session.candidates[last+1].offset-start+session.type.size<=readChunkBytes&&session.candidates[last+1].offset+session.type.size<=rangeEnd)last++;const auto size=static_cast<std::size_t>(session.candidates[last].offset-start+session.type.size);auto bytes=readExact(runtime,*running,start,size);for(;i<=last;i++)std::copy_n(bytes.data()+session.candidates[i].offset-start,session.type.size,values[i].data());}
  auto after=runtime.running(session.target.process);if(!after||!sameTarget(*after,session.target))throw std::runtime_error("CHEAT_TARGET_CHANGED");return values;
}
Json row(const MemoryScanner::Session& session,const MemoryScanner::Session::Candidate& candidate,const Bytes& value){return Json::object({{"resultId",candidate.id},{"value",display(session.type,value)},{"changed",!equal(value,candidate.previous,session.type.size)},{"writable",candidate.writable},{"modified",candidate.modified},{"frozen",candidate.frozen}});}
bool hasModified(const MemoryScanner::Session& session){return std::any_of(session.candidates.begin(),session.candidates.end(),[](const auto& item){return item.modified;});}
bool active(const MemoryScanner::Session::Segment& segment,std::size_t slot){return (segment.active[slot/8]&(1u<<(slot%8)))!=0;}
void setActive(MemoryScanner::Session::Segment& segment,std::size_t slot,bool value){auto& byte=segment.active[slot/8];const auto mask=static_cast<unsigned char>(1u<<(slot%8));if(value)byte|=mask;else byte&=static_cast<unsigned char>(~mask);}
void addCandidate(MemoryScanner::Session& session,std::uint64_t offset,std::size_t range,const Bytes& value){session.candidates.push_back({opaque(session.resultSecret,session.nextSerial++),offset,range,value,{}, {},session.target.ranges[range].writable,false,false});}
void materialize(MemoryScanner::Session& session){if(session.baseline.empty()||session.activeCount>maxMemoryScanResults)return;session.candidates.reserve(static_cast<std::size_t>(session.activeCount));for(const auto& segment:session.baseline)for(std::size_t slot=0;slot<segment.slots;slot++)if(active(segment,slot)){Bytes value{};std::copy_n(segment.previous.data()+slot*session.type.size,session.type.size,value.data());addCandidate(session,segment.start+slot*session.type.size,segment.range,value);}session.baseline.clear();}
bool keepValue(std::string_view mode,const Format& type,const Bytes& current,const Bytes& previous,const Bytes& expected){const auto comparison=compare(type,current,previous);return mode=="EXACT"?equal(current,expected,type.size):mode=="CHANGED"?!equal(current,previous,type.size):mode=="UNCHANGED"?equal(current,previous,type.size):mode=="INCREASED"?comparison>0:comparison<0;}
}

MemoryScanner::MemoryScanner(CheatRuntime& runtime,bool writeEnabled):runtime_(runtime),writeEnabled_(writeEnabled){}
MemoryScanner::~MemoryScanner(){try{restoreAll();}catch(...){ }}

Json MemoryScanner::target(){auto result=Json::object({{"available",false},{"enabled",runtime_.canRead()},{"writeEnabled",writeEnabled_&&runtime_.canWrite()},{"scope","MODULE_WRITABLE"}});if(!runtime_.canRead())return result;auto running=runtime_.running("eboot.bin");if(!running)return result;result.set("available",true);result.set("titleId",running->titleId);result.set("version",running->version);result.set("process",running->process);result.set("contentId",running->contentId);return result;}

Json MemoryScanner::start(const std::string& titleId,const std::string& version,const std::string& type,const std::string& mode,const std::string& value){
  if(!runtime_.canRead())throw std::runtime_error("MEMORY_SCANNER_DISABLED");if(!std::regex_match(titleId,titlePattern)||!std::regex_match(version,versionPattern))throw std::runtime_error("MEMORY_TARGET_INVALID");if(mode!="EXACT"&&mode!="UNKNOWN")throw std::runtime_error("MEMORY_SCAN_MODE_INVALID");if(session_&&hasModified(*session_))throw std::runtime_error("MEMORY_RESTORE_REQUIRED");auto running=runtime_.running("eboot.bin");if(!running||running->titleId!=titleId||running->version!=version)throw std::runtime_error("MEMORY_TARGET_MISMATCH");auto next=std::make_unique<Session>();next->id=randomHex(16);next->resultSecret=randomHex(16);next->target=*running;next->type=format(type);next->totalReadableBytes=validateRanges(*running);Bytes expected{};if(mode=="EXACT")expected=parse(next->type,value);else if(!value.empty())throw std::runtime_error("MEMORY_VALUE_UNEXPECTED");
  for(std::size_t r=0;r<running->ranges.size();r++){const auto& range=running->ranges[r];if(!range.readable||!range.writable||range.size<next->type.size)continue;auto cursor=range.offset;const auto misalignment=(running->moduleBase+cursor)%next->type.size;if(misalignment)cursor+=next->type.size-misalignment;const auto end=range.offset+range.size;if(cursor>end-next->type.size)continue;if(mode=="UNKNOWN"){Session::Segment segment;segment.range=r;segment.start=cursor;const auto byteCount=static_cast<std::size_t>(((end-cursor)/next->type.size)*next->type.size);segment.previous.resize(byteCount);segment.slots=byteCount/next->type.size;segment.active.assign((segment.slots+7)/8,0xff);for(std::size_t at=0;at<byteCount;at+=readChunkBytes){const auto size=std::min(readChunkBytes,byteCount-at);auto bytes=readExact(runtime_,*running,cursor+at,size);std::copy(bytes.begin(),bytes.end(),segment.previous.begin()+static_cast<std::ptrdiff_t>(at));}next->scannedBytes+=byteCount;next->activeCount+=segment.slots;next->baseline.push_back(std::move(segment));continue;}while(cursor<=end-next->type.size){auto size=static_cast<std::size_t>(std::min<std::uint64_t>(readChunkBytes,end-cursor));size-=size%next->type.size;if(size<next->type.size)break;auto bytes=readExact(runtime_,*running,cursor,size);next->scannedBytes+=size;for(std::size_t at=0;at+next->type.size<=bytes.size();at+=next->type.size){Bytes current{};std::copy_n(bytes.data()+at,next->type.size,current.data());if(equal(current,expected,next->type.size)){if(next->candidates.size()>=maxMemoryScanResults)throw std::runtime_error("MEMORY_SCAN_RESULT_LIMIT");addCandidate(*next,cursor+at,r,current);}}cursor+=size;}}
  if(mode=="EXACT")next->activeCount=next->candidates.size();else materialize(*next);auto after=runtime_.running(running->process);if(!after||!sameTarget(*after,*running))throw std::runtime_error("CHEAT_TARGET_CHANGED");session_=std::move(next);return watch(session_->id);
}

Json MemoryScanner::refine(const std::string& scanId,const std::string& mode,const std::string& value){
  auto& session=require(session_,scanId);if(hasModified(session))throw std::runtime_error("MEMORY_RESTORE_REQUIRED");const bool exactMode=mode=="EXACT";if(!exactMode&&mode!="CHANGED"&&mode!="UNCHANGED"&&mode!="INCREASED"&&mode!="DECREASED")throw std::runtime_error("MEMORY_SCAN_MODE_INVALID");Bytes expected{};if(exactMode)expected=parse(session.type,value);else if(!value.empty())throw std::runtime_error("MEMORY_VALUE_UNEXPECTED");if(!session.baseline.empty()){auto running=runtime_.running(session.target.process);if(!running||!sameTarget(*running,session.target))throw std::runtime_error("CHEAT_TARGET_CHANGED");std::uint64_t keptCount=0;for(auto& segment:session.baseline)for(std::size_t at=0;at<segment.previous.size();at+=readChunkBytes){const auto size=std::min(readChunkBytes,segment.previous.size()-at);auto bytes=readExact(runtime_,*running,segment.start+at,size);for(std::size_t local=0;local<size;local+=session.type.size){const auto slot=(at+local)/session.type.size;if(!active(segment,slot))continue;Bytes current{},previous{};std::copy_n(bytes.data()+local,session.type.size,current.data());std::copy_n(segment.previous.data()+at+local,session.type.size,previous.data());const bool keep=keepValue(mode,session.type,current,previous,expected);setActive(segment,slot,keep);if(keep){std::copy_n(current.data(),session.type.size,segment.previous.data()+at+local);keptCount++;}}}session.activeCount=keptCount;auto after=runtime_.running(session.target.process);if(!after||!sameTarget(*after,session.target))throw std::runtime_error("CHEAT_TARGET_CHANGED");materialize(session);return watch(scanId);}auto values=readCandidates(runtime_,session,session.candidates.size());std::vector<Session::Candidate> kept;kept.reserve(session.candidates.size());for(std::size_t i=0;i<session.candidates.size();i++)if(keepValue(mode,session.type,values[i],session.candidates[i].previous,expected)){session.candidates[i].previous=values[i];kept.push_back(std::move(session.candidates[i]));}session.candidates=std::move(kept);session.activeCount=session.candidates.size();return watch(scanId);
}

Json MemoryScanner::watch(const std::string& scanId){auto& session=require(session_,scanId);auto results=Json::array();std::size_t count=0;if(session.baseline.empty()){count=std::min(maxMemoryWatchResults,session.candidates.size());auto values=readCandidates(runtime_,session,count);for(std::size_t i=0;i<count;i++)results.add(row(session,session.candidates[i],values[i]));}else{auto running=runtime_.running(session.target.process);if(!running||!sameTarget(*running,session.target))throw std::runtime_error("CHEAT_TARGET_CHANGED");}return Json::object({{"scanId",session.id},{"titleId",session.target.titleId},{"version",session.target.version},{"process",session.target.process},{"scope","MODULE_WRITABLE"},{"valueType",session.type.name},{"candidateCount",static_cast<int64_t>(session.activeCount)},{"scannedBytes",static_cast<int64_t>(session.scannedBytes)},{"totalReadableBytes",static_cast<int64_t>(session.totalReadableBytes)},{"materialized",session.baseline.empty()},{"resultsTruncated",session.activeCount>count},{"results",results}});}

Json MemoryScanner::write(const std::string& scanId,const std::string& resultId,const std::string& value,bool freeze){
  if(!writeEnabled_||!runtime_.canWrite())throw std::runtime_error("MEMORY_WRITE_DISABLED");auto& session=require(session_,scanId);auto& candidate=selected(session,resultId);if(!candidate.writable||!within(session.target.ranges[candidate.range],candidate.offset,session.type.size))throw std::runtime_error("MEMORY_RESULT_READ_ONLY");if(!candidate.modified&&std::count_if(session.candidates.begin(),session.candidates.end(),[](const auto& item){return item.modified;})>=static_cast<std::ptrdiff_t>(maxMemoryModifiedResults))throw std::runtime_error("MEMORY_MODIFICATION_LIMIT");const auto desired=parse(session.type,value);auto running=runtime_.running(session.target.process);if(!running||!sameTarget(*running,session.target))throw std::runtime_error("CHEAT_TARGET_CHANGED");auto beforeVector=readExact(runtime_,*running,candidate.offset,session.type.size);Bytes before{};std::copy(beforeVector.begin(),beforeVector.end(),before.begin());const bool first=!candidate.modified;if(first){candidate.original=before;candidate.modified=true;}try{if(!equal(before,desired,session.type.size))runtime_.write(*running,candidate.offset,std::vector<unsigned char>(desired.begin(),desired.begin()+static_cast<std::ptrdiff_t>(session.type.size)));auto verified=readExact(runtime_,*running,candidate.offset,session.type.size);if(!std::equal(verified.begin(),verified.end(),desired.begin()))throw std::runtime_error("MEMORY_WRITE_VERIFY_FAILED");}catch(...){try{runtime_.write(*running,candidate.offset,beforeVector);if(readExact(runtime_,*running,candidate.offset,session.type.size)!=beforeVector)throw std::runtime_error("MEMORY_WRITE_ROLLBACK_FAILED");}catch(...){throw std::runtime_error("MEMORY_WRITE_ROLLBACK_FAILED");}if(first)candidate.modified=false;throw;}candidate.previous=desired;candidate.frozen=freeze;candidate.frozenValue=desired;return row(session,candidate,desired);
}

Json MemoryScanner::restore(const std::string& scanId,const std::string& resultId){if(!writeEnabled_||!runtime_.canWrite())throw std::runtime_error("MEMORY_WRITE_DISABLED");auto& session=require(session_,scanId);auto& candidate=selected(session,resultId);if(!candidate.modified)return row(session,candidate,candidate.previous);auto running=runtime_.running(session.target.process);if(!running||!sameTarget(*running,session.target))throw std::runtime_error("CHEAT_TARGET_CHANGED");auto original=std::vector<unsigned char>(candidate.original.begin(),candidate.original.begin()+static_cast<std::ptrdiff_t>(session.type.size));runtime_.write(*running,candidate.offset,original);if(readExact(runtime_,*running,candidate.offset,session.type.size)!=original)throw std::runtime_error("MEMORY_RESTORE_FAILED");candidate.previous=candidate.original;candidate.modified=false;candidate.frozen=false;return row(session,candidate,candidate.previous);}

std::size_t MemoryScanner::restoreAll(){if(!session_||!hasModified(*session_))return 0;if(!writeEnabled_||!runtime_.canWrite())throw std::runtime_error("MEMORY_WRITE_DISABLED");auto running=runtime_.running(session_->target.process);if(!running||!sameTarget(*running,session_->target)){session_.reset();return 0;}std::size_t restored=0;bool failed=false;for(auto& candidate:session_->candidates){if(!candidate.modified)continue;candidate.frozen=false;try{auto current=runtime_.running(session_->target.process);if(!current||!sameTarget(*current,session_->target))throw std::runtime_error("CHEAT_TARGET_CHANGED");auto original=std::vector<unsigned char>(candidate.original.begin(),candidate.original.begin()+static_cast<std::ptrdiff_t>(session_->type.size));runtime_.write(*current,candidate.offset,original);if(readExact(runtime_,*current,candidate.offset,session_->type.size)!=original)throw std::runtime_error("MEMORY_RESTORE_FAILED");candidate.previous=candidate.original;candidate.modified=false;restored++;}catch(...){failed=true;}}if(!hasModified(*session_))session_.reset();if(failed)throw std::runtime_error("MEMORY_RESTORE_ALL_FAILED");return restored;}

void MemoryScanner::reconcile()noexcept{if(!session_)return;const bool frozen=std::any_of(session_->candidates.begin(),session_->candidates.end(),[](const auto& item){return item.frozen;});if(!frozen&&!hasModified(*session_))return;const auto now=std::chrono::steady_clock::now();if(now<session_->nextReconcile)return;session_->nextReconcile=now+std::chrono::milliseconds(500);try{auto running=runtime_.running(session_->target.process);if(!running||!sameTarget(*running,session_->target)){session_.reset();return;}if(!frozen)return;for(auto& candidate:session_->candidates)if(candidate.frozen)try{auto current=readExact(runtime_,*running,candidate.offset,session_->type.size);if(!std::equal(current.begin(),current.end(),candidate.frozenValue.begin()))runtime_.write(*running,candidate.offset,std::vector<unsigned char>(candidate.frozenValue.begin(),candidate.frozenValue.begin()+static_cast<std::ptrdiff_t>(session_->type.size)));if(readExact(runtime_,*running,candidate.offset,session_->type.size)!=std::vector<unsigned char>(candidate.frozenValue.begin(),candidate.frozenValue.begin()+static_cast<std::ptrdiff_t>(session_->type.size)))candidate.frozen=false;}catch(...){candidate.frozen=false;}}catch(...){ }}
void MemoryScanner::clear(){if(session_&&hasModified(*session_))throw std::runtime_error("MEMORY_RESTORE_REQUIRED");session_.reset();}
}
